export const Armor = [
{
"Name": "Felle",
"RS": "0",
"BE": "0",
"Zusatz": "-",
"Gewicht": "1 Stn",
"Bereich": "",
"Preis": "-",
"Stability": "4",
"VN": ""
},
{
"Name": "Fellrüstung",
"RS": "0",
"BE": "0",
"Zusatz": "-",
"Gewicht": "1,5 Stn",
"Bereich": "",
"Preis": "20",
"Stability": "4",
"VN": "1 Kälteschutz; INI -1"
},
{
"Name": "nackt",
"RS": "0",
"BE": "0",
"Zusatz": "-",
"Gewicht": "1 Stn",
"Bereich": "",
"Preis": "-",
"Stability": "-",
"VN": ""
},
{
"Name": "normale Kleidung",
"RS": "0",
"BE": "0",
"Zusatz": "-",
"Gewicht": "1 Stn",
"Bereich": "",
"Preis": "-",
"Stability": "4",
"VN": ""
},
{
"Name": "Ifirnsmantel",
"RS": "1",
"BE": "0",
"Zusatz": "-1/-1",
"Gewicht": "2 Stn",
"Bereich": "",
"Preis": "150",
"Stability": "5",
"VN": "gegen (Zweihand-)Hiebwafffen RS 2; Kälteschutz 2; gegen Dolche, Fechtwaffen, Schwerter RS 0"
},
{
"Name": "Matrosenkleidung",
"RS": "1",
"BE": "0",
"Zusatz": "-1/-1",
"Gewicht": "2 Stn",
"Bereich": "",
"Preis": "25",
"Stability": "5",
"VN": "Wind erhöht Kältestufe nicht. Gegen Treffer mit 10+ TP kein RS."
},
{
"Name": "Schuppengewand",
"RS": "1",
"BE": "0",
"Zusatz": "-1/-1",
"Gewicht": "1 Stn",
"Bereich": "",
"Preis": "50",
"Stability": "5",
"VN": "1 Stufe Kälteschutz; gegen Dolche, Fechtwaffen, Schwerter RS 0"
},
{
"Name": "schwere Kleidung",
"RS": "1",
"BE": "0",
"Zusatz": "-1/-1",
"Gewicht": "2 Stn",
"Bereich": "",
"Preis": "-",
"Stability": "5",
"VN": ""
},
{
"Name": "Winterkleidung",
"RS": "1",
"BE": "0",
"Zusatz": "-1/-1",
"Gewicht": "2 Stn",
"Bereich": "",
"Preis": "-",
"Stability": "5",
"VN": ""
},
{
"Name": "Gambeson",
"RS": "2",
"BE": "1",
"Zusatz": "-",
"Gewicht": "3 Stn",
"Bereich": "",
"Preis": "105",
"Stability": "6",
"VN": "gegen (Zweihand-)Hiebwaffen RS 3; gegen Dolche, Fechtwaffen, Schwerter RS 1"
},
{
"Name": "Knochenrüstung",
"RS": "2",
"BE": "1",
"Zusatz": "-",
"Gewicht": "6 Stn",
"Bereich": "",
"Preis": "80",
"Stability": "6",
"VN": ""
},
{
"Name": "Stoffrüstung",
"RS": "2",
"BE": "1",
"Zusatz": "-",
"Gewicht": "3 Stn",
"Bereich": "",
"Preis": "75",
"Stability": "6",
"VN": ""
},
{
"Name": "Tuchrüstung",
"RS": "2",
"BE": "1",
"Zusatz": "-",
"Gewicht": "3 Stn",
"Bereich": "",
"Preis": "75",
"Stability": "6",
"VN": "Gegen Hiebwaffen und Zweihandhiebwaffen RS 3. In Flammen Körperbeherrschung zum Löschen -2."
},
{
"Name": "Wattierter Waffenrock",
"RS": "2",
"BE": "1",
"Zusatz": "-",
"Gewicht": "3 Stn",
"Bereich": "",
"Preis": "90",
"Stability": "6",
"VN": "gegen (Zweihand-)Hiebwaffen RS 3; wenn Brennend +1W3 SP"
},
{
"Name": "bornischer Eisenmantel",
"RS": "3",
"BE": "1",
"Zusatz": "-1/-1",
"Gewicht": "5 Stn",
"Bereich": "",
"Preis": "160",
"Stability": "8",
"VN": ""
},
{
"Name": "Eisenmantel",
"RS": "3",
"BE": "1",
"Zusatz": "-1/-1",
"Gewicht": "7 Stn",
"Bereich": "",
"Preis": "200",
"Stability": "8",
"VN": "gegen Dolche und Fechtwaffen RS 4; INI-Abzug -2 statt -1"
},
{
"Name": "Fünflagenharnisch",
"RS": "3",
"BE": "1",
"Zusatz": "-1/-1",
"Gewicht": "7 Stn",
"Bereich": "",
"Preis": "200",
"Stability": "8",
"VN": "gegen Dolche und Fechtwaffen RS4, GS-Abzug -2"
},
{
"Name": "Gladiatorenrüstung",
"RS": "3",
"BE": "1",
"Zusatz": "-1/-1",
"Gewicht": "4 Stn",
"Bereich": "",
"Preis": "100",
"Stability": "8",
"VN": "keine zus. Abzüge; bei Treffer W6: 1 RS 0, 2 RS 1, 3 - 6 RS 3"
},
{
"Name": "Havener Lederharnisch",
"RS": "3",
"BE": "1",
"Zusatz": "-1/-1",
"Gewicht": "5 Stn",
"Bereich": "",
"Preis": "180",
"Stability": "8",
"VN": "Körperbeherrschung (Balance und Kampfmanöver) nicht erschwert. Gegen Fernkampfwaffen nur RS 2."
},
{
"Name": "Hornrüstung",
"RS": "3",
"BE": "1",
"Zusatz": "-1/-1",
"Gewicht": "10 Stn",
"Bereich": "",
"Preis": "140",
"Stability": "8",
"VN": "-"
},
{
"Name": "Iryanrüstung",
"RS": "3",
"BE": "1",
"Zusatz": "-1/-1",
"Gewicht": "5 Stn",
"Bereich": "",
"Preis": "250",
"Stability": "8",
"VN": "Ist feuerfest, keine SP durch Feuer und Flammenangriffe. Pro Woche 8 h Pflege, sonst –2 GS, –2 INI."
},
{
"Name": "Krötenhaut",
"RS": "3",
"BE": "1",
"Zusatz": "-1/-1",
"Gewicht": "5 Stn",
"Bereich": "",
"Preis": "200",
"Stability": "8",
"VN": "Schwimmen und Körperbeherrschung (Balance) nicht erschwert. Gegen Fernkampfwaffen nur RS 2."
},
{
"Name": "Kurbul",
"RS": "3",
"BE": "1",
"Zusatz": "-1/-1",
"Gewicht": "7 Stn",
"Bereich": "",
"Preis": "180",
"Stability": "8",
"VN": "gegen (Zweihand-)Hiebwaffen, Kettenwaffen, Raufen, Schilde und Stangenwaffen RS 4; Proben auf GE -1"
},
{
"Name": "Lederharnisch",
"RS": "3",
"BE": "1",
"Zusatz": "-1/-1",
"Gewicht": "6 Stn",
"Bereich": "",
"Preis": "150",
"Stability": "8",
"VN": "Bietet eine Kälteschutzstufe. Bei Hitzestufe II+ weitere Hitzestufe (bis 4)."
},
{
"Name": "Lederrüstung",
"RS": "3",
"BE": "1",
"Zusatz": "-1/-1",
"Gewicht": "6 Stn",
"Bereich": "",
"Preis": "150",
"Stability": "8",
"VN": ""
},
{
"Name": "Lindwurmhaut",
"RS": "3",
"BE": "1",
"Zusatz": "-1/-1",
"Gewicht": "6 Stn",
"Bereich": "",
"Preis": "120",
"Stability": "8",
"VN": "Abzug GS oder INI ignorieren; Übler Geruch"
},
{
"Name": "Armschienen, Leder",
"RS": "3",
"BE": "",
"Zusatz": "",
"Gewicht": "1,2 Stn",
"Bereich": "Arm",
"Preis": "30",
"Stability": "8",
"VN": "-"
},
{
"Name": "Beinschienen, Leder",
"RS": "3",
"BE": "",
"Zusatz": "",
"Gewicht": "1,2 Stn",
"Bereich": "Bein",
"Preis": "30",
"Stability": "8",
"VN": "-"
},
{
"Name": "Gladiatorenhelm",
"RS": "3",
"BE": "",
"Zusatz": "",
"Gewicht": "0,6 Stn",
"Bereich": "Kopf",
"Preis": "15",
"Stability": "8",
"VN": "gegen Dolche, Fechtwaffen, Schwerter RS4; Hören und Sehen -1"
},
{
"Name": "Lederhelm",
"RS": "3",
"BE": "",
"Zusatz": "",
"Gewicht": "0,6 Stn",
"Bereich": "Kopf",
"Preis": "15",
"Stability": "8",
"VN": "-"
},
{
"Name": "Hartholzharnisch",
"RS": "4",
"BE": "2",
"Zusatz": "-",
"Gewicht": "10 Stn",
"Bereich": "",
"Preis": "300",
"Stability": "9",
"VN": "geschützt vor Ungeziefer; gegen (Zweihand-)Hiebwaffen nur RS 2"
},
{
"Name": "Holzrüstung",
"RS": "4",
"BE": "2",
"Zusatz": "-",
"Gewicht": "10 Stn",
"Bereich": "",
"Preis": "300",
"Stability": "9",
"VN": ""
},
{
"Name": "Kettenhemd",
"RS": "4",
"BE": "2",
"Zusatz": "-",
"Gewicht": "10 Stn",
"Bereich": "",
"Preis": "250",
"Stability": "13",
"VN": "Gegen Armbrüste, Bögen, Dolche und Schwerter RS 5. Sinnesschärfe zum bemerken +1."
},
{
"Name": "Kettenrüstung",
"RS": "4",
"BE": "2",
"Zusatz": "-",
"Gewicht": "12 Stn",
"Bereich": "",
"Preis": "250",
"Stability": "13",
"VN": ""
},
{
"Name": "Kettenweste",
"RS": "4",
"BE": "2",
"Zusatz": "-",
"Gewicht": "8 Stn",
"Bereich": "",
"Preis": "200",
"Stability": "13",
"VN": "gegen Armbrüste, Dolche, Schwerter RS 5; Sinnesschärfe zum Bemerken +1; bei Treffer W6: 1 RS 1, 2 RS 2, 3-6 RS 4"
},
{
"Name": "langes Kettenhemd",
"RS": "4",
"BE": "2",
"Zusatz": "-",
"Gewicht": "12 Stn",
"Bereich": "",
"Preis": "300",
"Stability": "13",
"VN": "gegen Armbrüste, Bögen, Dolche, Schwerter RS 5; bei anderen Kampftechniken W6: bei 5 und 6 RS 5; Sinnesschärfe zum Bemerken +1; Proben auf GE -1"
},
{
"Name": "Mammutonpanzer",
"RS": "4",
"BE": "2",
"Zusatz": "-",
"Gewicht": "10 Stn",
"Bereich": "",
"Preis": "500",
"Stability": "9",
"VN": "gegen Fernkampf RS 6; bei Patzer im Kampf RS -1"
},
{
"Name": "Skorpionhemd",
"RS": "4",
"BE": "2",
"Zusatz": "-",
"Gewicht": "12 Stn",
"Bereich": "",
"Preis": "300",
"Stability": "13",
"VN": "gegen Armbrüste, Bögen, Dolche, Schwerter RS 5; bei anderen Kampftechniken W6: bei 5 und 6 RS 5; Sinnesschärfe zum Bemerken +1; INI zus. -1"
},
{
"Name": "Spiegelpanzer",
"RS": "4",
"BE": "2",
"Zusatz": "-",
"Gewicht": "13 Stn",
"Bereich": "",
"Preis": "350",
"Stability": "13",
"VN": "Gegen Schwerter und Zweihandschwerter RS 5. Gegen Hiebwaffen und Zweihandhiebwaffen RS 2."
},
{
"Name": "Kettenbeinlinge",
"RS": "4",
"BE": "",
"Zusatz": "",
"Gewicht": "2,4 Stn",
"Bereich": "Bein",
"Preis": "50",
"Stability": "13",
"VN": "-"
},
{
"Name": "Kettenhaube",
"RS": "4",
"BE": "",
"Zusatz": "",
"Gewicht": "1,2 Stn",
"Bereich": "Kopf",
"Preis": "25",
"Stability": "13",
"VN": "gegen Armbrüste, Bögen, Dolche, Schwerter RS5; Sinnesschärfe zum Bemerken +1"
},
{
"Name": "Leichte Shakagra-Platte",
"RS": "5",
"BE": "2",
"Zusatz": "-",
"Gewicht": "18 Stn",
"Bereich": "",
"Preis": "400",
"Stability": "11",
"VN": ""
},
{
"Name": "Lamellar",
"RS": "5",
"BE": "2",
"Zusatz": "-1/-1",
"Gewicht": "17 Stn",
"Bereich": "",
"Preis": "380",
"Stability": "12",
"VN": "GE beim Reiten nicht um BE erschwert; gegen Dolche RS 2"
},
{
"Name": "Schuppenpanzer",
"RS": "5",
"BE": "2",
"Zusatz": "-1/-1",
"Gewicht": "18 Stn",
"Bereich": "",
"Preis": "400",
"Stability": "12",
"VN": "Gegen Hiebwaffen und Zweihandhiebwaffen RS 6. Gegen Dolche RS 2."
},
{
"Name": "Schuppenrüstung",
"RS": "5",
"BE": "2",
"Zusatz": "-1/-1",
"Gewicht": "18 Stn",
"Bereich": "",
"Preis": "400",
"Stability": "12",
"VN": ""
},
{
"Name": "Amazonenrüstung",
"RS": "6",
"BE": "3",
"Zusatz": "-",
"Gewicht": "8 Stn",
"Bereich": "",
"Preis": "600",
"Stability": "11",
"VN": "Die BE beträgt nur 2; nach Treffer WG:  1 RS0, 2 RS2, 3 RS4, 4-6 RS6"
},
{
"Name": "Bronzeharnisch",
"RS": "6",
"BE": "3",
"Zusatz": "-",
"Gewicht": "12 Stn",
"Bereich": "",
"Preis": "250",
"Stability": "11",
"VN": "gegen Dolche und Fechtwaffen RS 7; Körperbeherrschung (Kampfmanöver) -1"
},
{
"Name": "Garether Platte",
"RS": "6",
"BE": "3",
"Zusatz": "-",
"Gewicht": "34 Stn",
"Bereich": "",
"Preis": "1800",
"Stability": "11",
"VN": "gegen Dolche, Fechtwaffen, Schwerter RS 7; Abzüge auf GS und INI halbiert; gegen Hiebwaffen, Kettenwaffen und Zweihandhiebwaffen RS 4"
},
{
"Name": "Kürass",
"RS": "6",
"BE": "3",
"Zusatz": "-",
"Gewicht": "12 Stn",
"Bereich": "",
"Preis": "250",
"Stability": "11",
"VN": "gegen Dolche und Fechtwaffen RS 7; gegen Angriffe von hinten RS 1"
},
{
"Name": "leichte Platte",
"RS": "6",
"BE": "3",
"Zusatz": "-",
"Gewicht": "15 Stn",
"Bereich": "",
"Preis": "400",
"Stability": "11",
"VN": "Gegen Dolche und Fechtwaffen RS 7. Gegen Angriffe von hinten RS 1."
},
{
"Name": "Pantherrüstung",
"RS": "6",
"BE": "3",
"Zusatz": "-",
"Gewicht": "23 Stn",
"Bereich": "",
"Preis": "800",
"Stability": "11",
"VN": ""
},
{
"Name": "Plattenrüstung",
"RS": "6",
"BE": "3",
"Zusatz": "-",
"Gewicht": "25 Stn",
"Bereich": "",
"Preis": "750",
"Stability": "11",
"VN": ""
},
{
"Name": "Reiterharnisch",
"RS": "6",
"BE": "3",
"Zusatz": "-",
"Gewicht": "20 Stn",
"Bereich": "",
"Preis": "2000",
"Stability": "11",
"VN": "gegen Dolche und Fechtwaffe RS 8; gegen (Zweihand-)Hiebwaffen und Kettenwaffen RS 4"
},
{
"Name": "Schwere Shakagra-Plattenrüstung",
"RS": "6",
"BE": "3",
"Zusatz": "-",
"Gewicht": "25 Stn",
"Bereich": "",
"Preis": "750",
"Stability": "11",
"VN": ""
},
{
"Name": "Armschienen, Stahl",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "5 Stn",
"Bereich": "Arm",
"Preis": "150",
"Stability": "11",
"VN": "-"
},
{
"Name": "Baburiner Hut",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "2,5 Stn",
"Bereich": "Kopf",
"Preis": "75",
"Stability": "11",
"VN": "gegen Armbrüste, Bögen, Dolche, Schwerter RS 7; Hören -1"
},
{
"Name": "Beinschienen, Stahl",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "5 Stn",
"Bereich": "Bein",
"Preis": "150",
"Stability": "11",
"VN": "-"
},
{
"Name": "Drachenhelm",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "2,5 Stn",
"Bereich": "Kopf",
"Preis": "75",
"Stability": "11",
"VN": "gegen Dolche, Schwerter RS 7; ein Bestätigungswurf wiederholen; Hören und Sehen -2"
},
{
"Name": "Flügelhelm",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "2,5 Stn",
"Bereich": "Kopf",
"Preis": "75",
"Stability": "11",
"VN": "einen SchiP im Kampf für Gefährte, Hören -1"
},
{
"Name": "Maskenhelm",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "2,5 Stn",
"Bereich": "Kopf",
"Preis": "75",
"Stability": "11",
"VN": "Einschüchtern +1; Hören und Sehen -1"
},
{
"Name": "Morion",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "2,5 Stn",
"Bereich": "Kopf",
"Preis": "75",
"Stability": "11",
"VN": "-"
},
{
"Name": "Panzerhandschuhe",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "5 Stn",
"Bereich": "Arm",
"Preis": "150",
"Stability": "11",
"VN": "Raufen +1 TP; FF -2; Armbrüste und Bögen unmöglich"
},
{
"Name": "Schaller",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "2,5 Stn",
"Bereich": "Kopf",
"Preis": "75",
"Stability": "11",
"VN": "gegen Armbrüste, Bögen, Dolche, Schwerter RS7; Hören -1"
},
{
"Name": "Sturmhaube",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "2,5 Stn",
"Bereich": "Kopf",
"Preis": "75",
"Stability": "11",
"VN": "gegen Armbrüste, Bögen, Dolche, Schwerter RS7; Hören -1"
},
{
"Name": "Tellerhelm",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "2,5 Stn",
"Bereich": "Kopf",
"Preis": "75",
"Stability": "11",
"VN": "gegen herabfallende Trümmer RS+1 gesamt; nach Treffer W6: 1 RS0, 2 RS1, 3 RS3, 4-6 RS 6"
},
{
"Name": "Tobrischer Hut",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "2,5 Stn",
"Bereich": "Kopf",
"Preis": "75",
"Stability": "11",
"VN": "nach Treffer W6: 1 RS0, 2 RS1, 3-4 RS3, 5-6 RS 6"
},
{
"Name": "Topfhelm",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "2,5 Stn",
"Bereich": "Kopf",
"Preis": "75",
"Stability": "11",
"VN": "gegen (Zweihand-)Schwerter RS8; Hören und Sehen -3; mehr als 7 KR 1 Betäubung"
},
{
"Name": "Wolfshelm",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "2,5 Stn",
"Bereich": "Kopf",
"Preis": "75",
"Stability": "11",
"VN": "Willenskraft geg. Einschüchtern -1; Hören und Sehen -2; mehr als 10 KR 1 Betäubung"
},
{
"Name": "Zwergenhelm",
"RS": "6",
"BE": "",
"Zusatz": "",
"Gewicht": "2,5 Stn",
"Bereich": "Kopf",
"Preis": "75",
"Stability": "11",
"VN": "gegen groß und riesig RS7; Hören -2"
},
{
"Name": "Gestechrüstung",
"RS": "7",
"BE": "4",
"Zusatz": "-",
"Gewicht": "35 Stn",
"Bereich": "",
"Preis": "2500",
"Stability": "10",
"VN": "-"
},
{
"Name": "schwere Platte",
"RS": "7",
"BE": "4",
"Zusatz": "-",
"Gewicht": "32 Stn",
"Bereich": "",
"Preis": "2200",
"Stability": "10",
"VN": "gegen Dolche, Fechtwaffen RS 9; gegen (Zweihand-)Hiebwaffen, Kettenwaffen RS 5"
},
{
"Name": "Schaller mit Bart",
"RS": "7",
"BE": "",
"Zusatz": "",
"Gewicht": "2,5 Stn",
"Bereich": "Kopf",
"Preis": "75",
"Stability": "11",
"VN": "gegen Armbrüste, Bögen, Dolche, Schwerter RS8; Hören -1"
},
{
"Name": "Turnierrüstung",
"RS": "8",
"BE": "5",
"Zusatz": "-",
"Gewicht": "40 Stn",
"Bereich": "",
"Preis": "3000",
"Stability": "10",
"VN": "Etikette (Benehmen) zum Gegnerfordern CH +1. Benötigt zum Aufsteigen auf Reittier Hilfe und 10 KR. Sinnesschärfe (Suchen oder Wahrnehmen) für Hör- oder Sehsinn -2."
}];
