export const CraftingObjects = [
  {"name": "Beil/Handaxt", "complexity": 0, "type": "weapon", "talent": "Metallbearbeitung"},
  {"name": "Dreschflegel", "complexity": 0, "type": "weapon", "talent": "Holzbearbeitung"},
  {"name": "Dschadra", "complexity": 0, "type": "weapon", "talent": "Metallbearbeitung"},
  {"name": "Fackel", "complexity": 0, "type": "weapon", "talent": "Holzbearbeitung"},
  {"name": "Fuhrmannspeitsche", "complexity": 0, "type": "weapon", "talent": "Lederbearbeitung"},
  {"name": "Hirtenstab", "complexity": 0, "type": "weapon", "talent": "Holzbearbeitung"},
  {"name": "Holzschild", "complexity": 0, "type": "weapon", "talent": "Holzbearbeitung"},
  {"name": "Holzspeer", "complexity": 0, "type": "weapon", "talent": "Holzbearbeitung"},
  {"name": "Kampfstab", "complexity": 0, "type": "weapon", "talent": "Holzbearbeitung"},
  {"name": "Keule", "complexity": 0, "type": "weapon", "talent": "Holzbearbeitung"},
  {"name": "Knüppel", "complexity": 0, "type": "weapon", "talent": "Holzbearbeitung"},
  {"name": "Kriegsflegel", "complexity": 0, "type": "weapon", "talent": "Metallbearbeitung"},
  {"name": "Sturmsense", "complexity": 0, "type": "weapon", "talent": "Metallbearbeitung"},
  {"name": "Lederschild", "complexity": 0, "type": "weapon", "talent": "Lederbearbeitung"},
  {"name": "Magierstab (alle Größen)", "complexity": 0, "type": "weapon", "talent": "Holzbearbeitung"},
  {"name": "Nudel-/Teigholz", "complexity": 0, "type": "weapon", "talent": "Holzbearbeitung"},
  {"name": "Schlagring", "complexity": 0, "type": "weapon", "talent": "Metallbearbeitung"},
  {"name": "Messer", "complexity": 0, "type": "weapon", "talent": "Metallbearbeitung"},
  {"name": "Schleuder", "complexity": 0, "type": "weapon", "talent": "Lederbearbeitung"},
  {"name": "Sense", "complexity": 0, "type": "weapon", "talent": "Metallbearbeitung"},
  {"name": "Sichel", "complexity": 0, "type": "weapon", "talent": "Metallbearbeitung"},
  {"name": "Speer", "complexity": 0, "type": "weapon", "talent": "Metallbearbeitung"},
  {"name": "Wurfkeule", "complexity": 0, "type": "weapon", "talent": "Holzbearbeitung"},
  {"name": "Wurfspeer", "complexity": 0, "type": "weapon", "talent": "Holzbearbeitung"},
  {"name": "Anderthalbhänder", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Barbarenschwert", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Barbarenstreitaxt", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Brabakbengel", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Breitschwert", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Dolch", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Doppelkhunchomer", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Dreizack", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Entermesser", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Großer Sklaventod", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Großschild", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Haumesser", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Hellebarde", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Khunchomer", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Kriegshammer", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Kriegslanze", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Kurzbogen", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Holzbearbeitung"},
  {"name": "Kurzschwert", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Langbogen", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Langschwert", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Leichte Armbrust", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Holzbearbeitung"},
  {"name": "Linkhand", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Molokdeschnaja", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Morgenstern", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Orknase", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Parazonium", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Rabenschnabel", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Rapier", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Säbel", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Schmiedehammer", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Schneidzahn", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Schwerer Dolch", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Scimshar", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Sklaventod", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Streitaxt", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Streitkolben", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Thorwalerschild", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Holzbearbeitung"},
  {"name": "Turnierlanze", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Holzbearbeitung"},
  {"name": "Turnierschwert", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Turnierzweihänder", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Waqqif", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Wurfbeil", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Wurfdolch", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Wurfring", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Wurfscheibe", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Wurfstern", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Zweihänder", "complexity": 1, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Balestrina", "ap": 4, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Basiliskenzunge", "ap": 2, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Drachenzahn", "ap": 2, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Eisenwalder", "ap": 4, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Elfenbogen", "ap": 5, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Holzbearbeitung"},
  {"name": "Felsspalter", "ap": 3, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Florett", "ap": 3, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Handarmbrust", "ap": 3, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Kompositbogen", "ap": 4, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Holzbearbeitung"},
  {"name": "Lindwurmschläger", "ap": 3, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Pailos", "ap": 4, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Robbentöter", "ap": 3, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Rondrakamm", "ap": 4, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Schwere Armbrust", "ap": 4, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Sonnenzepter", "ap": 2, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Tuzakmesser", "ap": 4, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Wolfsmesser", "ap": 3, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Zweililien", "ap": 2, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Zwergenschlägel", "ap": 3, "complexity": 2, "type": "weapon", "sf": "Waffenbau", "talent": "Metallbearbeitung"},
  {"name": "Stoffrüstung", "complexity": 0, "type": "armor", "talent": "Stoffbearbeitung"},
  {"name": "Hornrüstungen", "complexity": 0, "type": "armor", "talent": "Holzbearbeitung"},
  {"name": "Knochenrüstungen", "complexity": 0, "type": "armor", "talent": "Holzbearbeitung"},
  {"name": "Lederrüstung", "complexity": 1, "type": "armor", "sf": "Rüstungsbau", "talent": "Lederbearbeitung"},
  {"name": "Kettenrüstung", "complexity": 1, "type": "armor", "sf": "Rüstungsbau", "talent": "Metallbearbeitung"},
  {"name": "Holzrüstung", "complexity": 1, "type": "armor", "sf": "Rüstungsbau", "talent": "Holzbearbeitung"},
  {"name": "Schuppenrüstung", "complexity": 1, "type": "armor", "sf": "Rüstungsbau", "talent": "Lederbearbeitung"},
  {"name": "Plattenrüstung", "complexity": 1, "type": "armor", "sf": "Rüstungsbau", "talent": "Metallbearbeitung"},
  {"name": "Turnierrüstung", "complexity": 2, "type": "armor", "sf": "Rüstungsbau", "talent": "Metallbearbeitung", "ap": 5}
];

