export const Fernkampfwaffen = [{
  "Name": "Balestra",
  "Technik": "Armbrüste",
  "Lade": "4 Akt",
  "Schaden": "2W6+2",
  "Reichweite": "10/35/60",
  "Munition": "Kugeln",
  "Gewicht": "2,75 Stn",
  "Preis": "200",
  "BF": "6",
  "VN": "Abzüge für klein und winzig sinken um 1. Bei gewürfelter 20 immer schwere Ladehemmung, 2 Aktionen nötig."
},
{
  "Name": "Balestrina",
  "Technik": "Armbrüste",
  "Lade": "2 Akt.",
  "Schaden": "1W6+4",
  "Reichweite": "5/25/40",
  "Munition": "Kugeln",
  "Gewicht": "0,75 Stn",
  "Preis": "120",
  "BF": "6",
  "VN": "Abzüge für klein und winzig sinken um 1. Bei gewürfelter 20 immer schwere Ladehemmung, 2 Aktionen nötig."
},
{
  "Name": "Balläster",
  "Technik": "Armbrüste",
  "Lade": "2 Akt.",
  "Schaden": "1W6+3",
  "Reichweite": "20/60/100",
  "Munition": "Kugeln",
  "Gewicht": "3 Stn",
  "Preis": "200",
  "BF": "6",
  "VN": "Bis 5 Schritt +2 TP. Gegen Vögel +1 TP. Bei gewürfelter 20 immer schwere Ladehemmung, 2 Aktionen nötig."
},
{
  "Name": "Eisenwalder",
  "Technik": "Armbrüste",
  "Lade": "2/10 Akt.",
  "Schaden": "1W6+4",
  "Reichweite": "10/50/80",
  "Munition": "Bolzen",
  "Gewicht": "3,75 Stn",
  "Preis": "500",
  "BF": "6",
  "VN": "Beim Zielen Bonus von 3 (bis max 4). Gewürfelte 20 führt zu schwerer Ladehemmung, benötigt 3 Aktionen."
},
{
  "Name": "Handarmbrust",
  "Technik": "Armbrüste",
  "Lade": "3 Akt.",
  "Schaden": "1W6+3",
  "Reichweite": "5/25/40",
  "Munition": "Bolzen",
  "Gewicht": "0,75 Stn",
  "Preis": "100",
  "BF": "6",
  "VN": "Bis 2 Schritt +1 TP. Auf Distanz weit sinkt TP um weiteren Punkt."
},
{
  "Name": "leichte Armbrust",
  "Technik": "Armbrüste",
  "Lade": "8 Akt.",
  "Schaden": "1W6+6",
  "Reichweite": "10/50/80",
  "Munition": "Bolzen",
  "Gewicht": "3,25 Stn",
  "Preis": "180",
  "BF": "6",
  "VN": "-"
},
{
  "Name": "Mittelschwere Rotze",
  "Technik": "Armbrüste",
  "Lade": "50 Akt",
  "Schaden": "3W20+3",
  "Reichweite": "50/200/800",
  "Munition": "",
  "Gewicht": "",
  "Preis": "8000",
  "BF": "10",
  "VN": ""
},
{
  "Name": "schwere Armbrust",
  "Technik": "Armbrüste",
  "Lade": "15 Akt.",
  "Schaden": "2W6+6",
  "Reichweite": "20/100/160",
  "Munition": "Bolzen",
  "Gewicht": "7,25 Stn",
  "Preis": "360",
  "BF": "6",
  "VN": "Auf nahe Distanz TP +1. Auf weite Distanz TP -1."
},
{
  "Name": "Windenarmbrust",
  "Technik": "Armbrüste",
  "Lade": "25 Akt",
  "Schaden": "2W6+6",
  "Reichweite": "25/100/200",
  "Munition": "Bolzen",
  "Gewicht": "7,25 Stn",
  "Preis": "450",
  "BF": "6",
  "VN": "nah zus. TP +2, weit TP zus. -2"
},
{
  "Name": "Blasrohr",
  "Technik": "Blasrohre",
  "Lade": "2 Akt.",
  "Schaden": "1W2",
  "Reichweite": "5/20/40",
  "Munition": "Blasrohrpfeile",
  "Gewicht": "0,5 Stn",
  "Preis": "40",
  "BF": "10",
  "VN": "-"
},
{
  "Name": "Albernischer Langbogen",
  "Technik": "Bögen",
  "Lade": "2 Akt",
  "Schaden": "1W6+8",
  "Reichweite": "20/100/160",
  "Munition": "Pfeile",
  "Gewicht": "0,75 Stn",
  "Preis": "80",
  "BF": "4",
  "VN": "Reichweite Ballistischer Schuss +20 Schritt. Gegen RS 4+ +1. Nicht vom Reittier aus einsetzbar. In Wäldern (Gelände schwierig oder schlechter) zusätzliche
}
{
  "Name": "Elfenbogen",
  "Technik": "Bögen",
  "Lade": "1 Akt",
  "Schaden": "1W6+5",
  "Reichweite": "50/100/200",
  "Munition": "Pfeile",
  "Gewicht": "0,5 Stn",
  "Preis": "400",
  "BF": "4",
  "VN": "Präziser Schuss 1 erleichtert. Für Nichtelfen –2 auf FK. Nicht vom Rücken eines Reittiers einsetzbar."
},
{
  "Name": "Kompositbogen",
  "Technik": "Bögen",
  "Lade": "2 Akt",
  "Schaden": "1W6+7",
  "Reichweite": "20/100/160",
  "Munition": "Pfeile",
  "Gewicht": "0,75 Stn",
  "Preis": "160",
  "BF": "4",
  "VN": "Erschwernis aus Entfernung sinkt um 1 (nicht unter 0). In Wäldern (Gelände schwierig oder schlechter) zusätzliche Erschwernis von 2."
},
{
  "Name": "Kriegsbogen",
  "Technik": "Bögen",
  "Lade": "2 Akt",
  "Schaden": "1W6+8",
  "Reichweite": "25/50/100",
  "Munition": "Pfeile",
  "Gewicht": "1 Stn",
  "Preis": "100",
  "BF": "4",
  "VN": "bis 50 m TP +2, je KK < 16 FK -1"
},
{
  "Name": "Kurzbogen",
  "Technik": "Bögen",
  "Lade": "1 Akt",
  "Schaden": "1W6+4",
  "Reichweite": "10/50/80",
  "Munition": "Pfeile",
  "Gewicht": "0,5 Stn",
  "Preis": "45",
  "BF": "4",
  "VN": "-"
},
{
  "Name": "Langbogen",
  "Technik": "Bögen",
  "Lade": "2 Akt",
  "Schaden": "1W6+8",
  "Reichweite": "20/100/160",
  "Munition": "Pfeile",
  "Gewicht": "0,75 Stn",
  "Preis": "80",
  "BF": "4",
  "VN": "Ballistischer Schuss nicht erschwert. Nicht vom Reittier aus einsetzbar. In Wäldern (Gelände schwierig oder schlechter) zusätzliche Erschwernis von 2."
},
{
  "Name": "Nostrischer Langbogen",
  "Technik": "Bögen",
  "Lade": "2 Akt",
  "Schaden": "1W6+8",
  "Reichweite": "20/120/180",
  "Munition": "Pfeile",
  "Gewicht": "1 Stn",
  "Preis": "100",
  "BF": "4",
  "VN": "Schild wird bei Parade durchschlagen, wenn 1-3 auf W6 - einfacher Schildbonus auf RS. In Wäldern (Gelände schwierig oder schlechter) zusätzliche Erschwernis von
}
{
  "Name": "Diskus",
  "Technik": "Diskusse",
  "Lade": "2 Akt.",
  "Schaden": "1W6+2",
  "Reichweite": "5/25/40",
  "Munition": "",
  "Gewicht": "0,75 Stn",
  "Preis": "25",
  "BF": "12",
  "VN": "-"
},
{
  "Name": "Feuerspeien",
  "Technik": "Feuerspeien",
  "Lade": "1 Akt",
  "Schaden": "1W6",
  "Reichweite": "1/2/3",
  "Munition": "speziell",
  "Gewicht": "0 Stn",
  "Preis": "0",
  "BF": "-",
  "VN": ""
},
{
  "Name": "Fledermaus",
  "Technik": "Schleudern",
  "Lade": "2 Akt",
  "Schaden": "spez.",
  "Reichweite": "5/10/20",
  "Munition": "",
  "Gewicht": "0,5 Stn",
  "Preis": "10",
  "BF": "4",
  "VN": "Opfer Liegend oder Fixiert Aktionen -1, Nichtzwerge FK -2, kein Zielen möglich"
},
{
  "Name": "Schleuder",
  "Technik": "Schleudern",
  "Lade": "2 Akt",
  "Schaden": "1W6+2",
  "Reichweite": "5/25/60",
  "Munition": "Steinchen",
  "Gewicht": "0,25 Stn",
  "Preis": "5",
  "BF": "4",
  "VN": "-"
},
{
  "Name": "Stabschleuder",
  "Technik": "Schleudern",
  "Lade": "2 Akt",
  "Schaden": "1W6+3",
  "Reichweite": "10/20/60",
  "Munition": "Steinchen",
  "Gewicht": "1 Stn",
  "Preis": "15",
  "BF": "4",
  "VN": "Zielen bringt zus. +1, auf weit TP zus. -2"
},
{
  "Name": "Windhager Schleuder",
  "Technik": "Schleudern",
  "Lade": "2 Akt",
  "Schaden": "1W6+2",
  "Reichweite": "5/25/60",
  "Munition": "Steinchen",
  "Gewicht": "0,25 Stn",
  "Preis": "5",
  "BF": "4",
  "VN": "Getroffener Reiter ab 1 SP Reiten (Kampfmanöver) oder Fall. Bei 19 auf FK Bestätigungswurf ob Patzer."
},
{
  "Name": "Albernisches Wurfbeil",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W6+5",
  "Reichweite": "2/10/25",
  "Munition": "",
  "Gewicht": "1,25 Stn",
  "Preis": "100",
  "BF": "10",
  "VN": "Distanz weit kein TP-Malus. Distanz kurz kein Bonus."
},
{
  "Name": "Apfel",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W3",
  "Reichweite": "2/4/8",
  "Munition": "",
  "Gewicht": "",
  "Preis": "0",
  "BF": "10",
  "VN": ""
},
{
  "Name": "Bierkrug",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W3+1",
  "Reichweite": "2/4/8",
  "Munition": "",
  "Gewicht": "",
  "Preis": "",
  "BF": "10",
  "VN": ""
},
{
  "Name": "Borndorn",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W6+2",
  "Reichweite": "2/10/15",
  "Munition": "",
  "Gewicht": "0,75 Stn",
  "Preis": "65",
  "BF": "10",
  "VN": "auf 5/15/30 TP -2, RS4+ RS +1"
},
{
  "Name": "Efferdbart",
  "Technik": "Wurfwaffen",
  "Lade": "2 Akt",
  "Schaden": "1W6+3",
  "Reichweite": "2/10/15",
  "Munition": "",
  "Gewicht": "2 Stn",
  "Preis": "100",
  "BF": "10",
  "VN": ""
},
{
  "Name": "Gaoraith",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W6+5",
  "Reichweite": "2/10/25",
  "Munition": "",
  "Gewicht": "1,25 Stn",
  "Preis": "100",
  "BF": "10",
  "VN": "Distanz weit kein TP-Malus. Distanz kurz kein Bonus."
},
{
  "Name": "Geschirr",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W3+1",
  "Reichweite": "2/4/8",
  "Munition": "",
  "Gewicht": "",
  "Preis": "",
  "BF": "10",
  "VN": ""
},
{
  "Name": "Granatapfel",
  "Technik": "Wurfwaffen",
  "Lade": "2 Akt",
  "Schaden": "spez.",
  "Reichweite": "2/4/8",
  "Munition": "",
  "Gewicht": "1 Stn",
  "Preis": "200",
  "BF": "10",
  "VN": "-"
},
{
  "Name": "Jonglierball",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W3",
  "Reichweite": "4/8/16",
  "Munition": "",
  "Gewicht": "0,2 Stn",
  "Preis": "0,5",
  "BF": "10",
  "VN": ""
},
{
  "Name": "Jonglierball mit Gewichten",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W3+1",
  "Reichweite": "2/4/8",
  "Munition": "",
  "Gewicht": "0,3 Stn",
  "Preis": "0,8",
  "BF": "10",
  "VN": ""
},
{
  "Name": "Magierkugel",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W6+1",
  "Reichweite": "3/6/9",
  "Munition": "",
  "Gewicht": "2 Stn",
  "Preis": "30",
  "BF": "10",
  "VN": ""
},
{
  "Name": "Schneidzahn",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W6+4",
  "Reichweite": "2/10/15",
  "Munition": "",
  "Gewicht": "1 Stn",
  "Preis": "80",
  "BF": "10",
  "VN": "Beim Wuchtigen Wurf Schadensschwelle um 1 kleiner. Auf weite Distanz zusätzlich um 1 erschwert."
},
{
  "Name": "Stein",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W6",
  "Reichweite": "2/10/15",
  "Munition": "",
  "Gewicht": "1 Stn",
  "Preis": "0",
  "BF": "10",
  "VN": ""
},
{
  "Name": "Steinchen",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W3",
  "Reichweite": "2/4/8",
  "Munition": "",
  "Gewicht": "",
  "Preis": "0",
  "BF": "10",
  "VN": ""
},
{
  "Name": "Vase",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W3+1",
  "Reichweite": "2/4/8",
  "Munition": "",
  "Gewicht": "2 Stn",
  "Preis": "1",
  "BF": "10",
  "VN": ""
},
{
  "Name": "Wurfbeil",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W6+3",
  "Reichweite": "2/10/15",
  "Munition": "",
  "Gewicht": "0,75 Stn",
  "Preis": "50",
  "BF": "10",
  "VN": "-"
},
{
  "Name": "Wurfdolch",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W6+1",
  "Reichweite": "2/10/15",
  "Munition": "",
  "Gewicht": "0,5 Stn",
  "Preis": "45",
  "BF": "10",
  "VN": "-"
},
{
  "Name": "Wurfkeule",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W6+2",
  "Reichweite": "2/10/15",
  "Munition": "",
  "Gewicht": "1 Stn",
  "Preis": "5",
  "BF": "10",
  "VN": "Bei 6+ SP Körperbeherrschung (Balance) -(SP - 6), sonst Liegend. Gegen RS 4+ –2 TP."
},
{
  "Name": "Wurfmesser",
  "Technik": "Wurfwaffen",
  "Lade": "1 Alt",
  "Schaden": "1W6+1",
  "Reichweite": "2/5/10",
  "Munition": "",
  "Gewicht": "0,5 Stn",
  "Preis": "30",
  "BF": "10",
  "VN": "Präziser Wurf +1, auf weit TP zus -1"
},
{
  "Name": "Wurfnetz",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt.",
  "Schaden": "spez.",
  "Reichweite": "1/3/5",
  "Munition": "",
  "Gewicht": "2 Stn",
  "Preis": "35",
  "BF": "10",
  "VN": "Nur ausweichen möglich, keine Parade mit Schild. Bei Patzer selbst gefesselt."
},
{
  "Name": "Wurfring",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W6+1",
  "Reichweite": "2/10/15",
  "Munition": "",
  "Gewicht": "0,25 Stn",
  "Preis": "30",
  "BF": "10",
  "VN": "+1 TP gegen Humanoide mit RS 0. FK 19 erfordert Bestätigungswurf für Patzer."
},
{
  "Name": "Wurfscheibe",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W6+1",
  "Reichweite": "2/10/15",
  "Munition": "",
  "Gewicht": "0,25 Stn",
  "Preis": "30",
  "BF": "10",
  "VN": "FK um 1 erleichtert. FK 19 erfordert Bestätigungswurf für Patzer."
},
{
  "Name": "Wurfspeer",
  "Technik": "Wurfwaffen",
  "Lade": "2 Akt",
  "Schaden": "2W6+2",
  "Reichweite": "5/25/40",
  "Munition": "",
  "Gewicht": "0,75 Stn",
  "Preis": "40",
  "BF": "10",
  "VN": "Bei 10+ SP Selbstbeherrschung (Handlungsfähigkeit bewahren) -(SP - 10), sonst Liegend. Schnellladen nicht möglich."
},
{
  "Name": "Wurfstern",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W6+1",
  "Reichweite": "2/10/15",
  "Munition": "",
  "Gewicht": "0,25 Stn",
  "Preis": "30",
  "BF": "10",
  "VN": "Bleibt bei 6+ SP im Körper stecken, bis Ende nächste KR -1 auf AT, PA, AW und FK für Getroffenen. FK 19 erfordert Bestätigungswurf für Patzer."
},
{
  "Name": "Zauberkugel",
  "Technik": "Wurfwaffen",
  "Lade": "1 Akt",
  "Schaden": "1W6+1",
  "Reichweite": "3/6/9",
  "Munition": "",
  "Gewicht": "2 Stn",
  "Preis": "30",
  "BF": "10",
  "VN": ""
}];
