export const Regions = {
  "Hoher Norden": [
    "Ehernes Schwert",
    "Grüne Ebene",
    "Eis",
    "ganz Aventurien",
    "Zwischen Lowangen-Selem",
    "keine natürlichen Vorkommen",
    "Svelltland",
    "südlich von Riva",
    "zwischen Gerasim und Mengbilla",
    "nördlich der Khôm",
    "nördlich von Havena-Perricum",
    "nördlich von Thorwal-Festum",
    "nördlich von Grangor-Elburum",
    "südlich der Gelben Sichel",
    "zwischen Salamandersteinen und Ongalo-Bergen",
    "zwischen Riva und Mengbilla",
    "zwischen Riva und Al‘Anfa",
    "südlich von Gerasim",
    "südlich des Blauen Sees",
    "nördlich des Yaquirs",
    "südlich von Festum",
    "Weiden",
    "Nord- und Mittelaventurien",
    "Wälder um die Salamandersteine",
    "andere Seen",
    "Neunaugensee",
    "Nordaventurien",
    "Hochgebirge Aventuriens"
  ],
  "Khôm & Gor": [
    "Gor",
    "Hochgebirge Aventuriens",
    "Szintotal",
    "Wüsten",
    "östliche Khôm",
    "keine natürlichen Vorkommen",
    "andere Seen",
    "Südl. Eternen",
    "Unauer Berge",
    "Shadif",
    "Khômrand",
    "ganz Aventurien",
    "Südliche Khôm",
    "Khômwüste und Randgebiete",
    "Khoramgebirge"
  ],
  "Maraskan": [
    "Hochgebirge Aventuriens",
    "südlich von Festum",
    "zwischen Gerasim und Mengbilla",
    "Küste südlich von Thorwal",
    "Ostaventurien",
    "Süd- und Mittelaventurien",
    "nördlich von Grangor-Elburum",
    "südlich der Gelben Sichel",
    "zwischen Salamandersteinen und Ongalo-Bergen",
    "zwischen Riva und Mengbilla",
    "zwischen Riva und Al‘Anfa",
    "südlich von Gerasim",
    "südlich des Blauen Sees",
    "nördlich der Khôm",
    "südlich von Riva",
    "nördlich des Yaquirs",
    "andere Seen",
    "Südaventurien",
    "Maraskan",
    "keine natürlichen Vorkommen",
    "Südliches Maraskan und umliegende Inseln",
    "ganz Aventurien",
    "Maraskankette",
    "Maraskan + umliegende Inseln"
  ],
  "Meer": [
    "keine natürlichen Vorkommen",
    "Perlenmeer zwischen Selem und Charypso",
    "Altoum",
    "Golf von Perricum"
  ],
  "Mittelreich": [
    "Eisenwald",
    "Garetien",
    "Garetien bis Echsensümpfe",
    "Süd- und Mittelaventurien",
    "Weiden",
    "nördlich von Thorwal-Festum",
    "nördich von Nostria-Vallusa",
    "nördlich von Grangor-Elburum",
    "nördlich Nostria-Vallusa",
    "andere Seen",
    "Darpat",
    "südlich von Riva",
    "Darpatien",
    "zwischen Gerasim und Mengbilla",
    "nördlich von Havena-Perricum",
    "Zwischen Lowangen-Selem",
    "nördlich des Yaquirs",
    "ganz Aventurien",
    "südlich von Havena",
    "südlich der Gelben Sichel",
    "zwischen Salamandersteinen und Ongalo-Bergen",
    "zwischen Riva und Mengbilla",
    "zwischen Riva und Al‘Anfa",
    "südlich von Gerasim",
    "südlich des Blauen Sees",
    "südlich von Havena-Perricum",
    "südlich von Festum",
    "nördlich der Khôm",
    "Hochgebirge Aventuriens",
    "keine natürlichen Vorkommen",
    "Nord- und Mittelaventurien",
    "Kosch",
    "Mittelaventurien zwischen Trallop und Punin"
  ],
  "Mittlerer Osten": [
    "Beilunk",
    "Süd- und Mittelaventurien",
    "Ostaventurien",
    "südlich von Riva",
    "Yslisee",
    "nördich von Nostria-Vallusa",
    "nördlich von Thorwal-Festum",
    "nördlich von Grangor-Elburum",
    "nördlich Nostria-Vallusa",
    "ganz Aventurien",
    "nördlich von Havena-Perricum",
    "südlich von Festum",
    "südlich der Gelben Sichel",
    "zwischen Salamandersteinen und Ongalo-Bergen",
    "zwischen Riva und Mengbilla",
    "zwischen Riva und Al‘Anfa",
    "südlich von Gerasim",
    "zwischen Gerasim und Mengbilla",
    "südlich des Blauen Sees",
    "nördlich des Yaquirs",
    "nördliches Tobrien",
    "nördlich der Khôm",
    "Radrom",
    "andere Seen",
    "keine natürlichen Vorkommen",
    "Warunkei",
    "Zwischen Lowangen-Selem",
    "Küste südlich von Thorwal",
    "Schwarz-Tobrien",
    "Tobrien",
    "Hochgebirge Aventuriens"
  ],
  "Mittlerer Westen": [
    "Albernia",
    "Westküste zwischen Salza und Mengbilla",
    "Nordmarken",
    "zwischen Gerasim und Mengbilla",
    "nördlich von Havena-Perricum",
    "Nostria",
    "südlich von Havena-Perricum",
    "südlich von Havena",
    "nördlich der Khôm",
    "nördlich von Thorwal-Festum",
    "südlich der Gelben Sichel",
    "zwischen Salamandersteinen und Ongalo-Bergen",
    "zwischen Riva und Mengbilla",
    "zwischen Riva und Al‘Anfa",
    "südlich von Gerasim",
    "südlich des Blauen Sees",
    "südlich von Riva",
    "nördich von Nostria-Vallusa",
    "nördlich von Grangor-Elburum",
    "nördlich Nostria-Vallusa",
    "andere Seen",
    "ganz Aventurien",
    "Thorwal",
    "nördlich des Yaquirs",
    "Süd- und Mittelaventurien",
    "südlich von Festum",
    "keine natürlichen Vorkommen",
    "Andergast",
    "Zwischen Lowangen-Selem",
    "Küste südlich von Thorwal",
    "Hochgebirge Aventuriens",
    "Westküste Aventuriens",
    "Windhag",
    "Phecanowald",
    "Windhaggebirge"
  ],
  "Nordosten": [
    "Bornland",
    "Nord- und Mittelaventurien",
    "Totenmoor",
    "nördlich von Thorwal-Festum",
    "zwischen Gerasim und Mengbilla",
    "südlich der Gelben Sichel",
    "zwischen Salamandersteinen und Ongalo-Bergen",
    "zwischen Riva und Mengbilla",
    "zwischen Riva und Al‘Anfa",
    "südlich von Gerasim",
    "südlich des Blauen Sees",
    "nördlich des Yaquirs",
    "nördlich von Grangor-Elburum",
    "südlich von Festum",
    "nördlich der Khôm",
    "südlich von Riva",
    "Ostaventurien",
    "nördlich von Havena-Perricum",
    "keine natürlichen Vorkommen",
    "Nordostaventurien von der Letta bis zur Tobimora",
    "Nordaventurien",
    "andere Seen",
    "ganz Aventurien",
    "Zwischen Lowangen-Selem",
    "Ehernes Schwert",
    "Eis",
    "Hochgebirge Aventuriens"
  ],
  "Nordwesten": [
    "Eis",
    "Svelltland",
    "nördlich von Thorwal-Festum",
    "südlich von Festum",
    "nördlich von Grangor-Elburum",
    "Svelltsümpfe",
    "Finsterkamm",
    "südlich von Riva",
    "Zwischen Lowangen-Selem",
    "Nord- und Mittelaventurien",
    "Thorwal",
    "Orkland",
    "nördlich der Khôm",
    "zwischen Gerasim und Mengbilla",
    "südlich der Gelben Sichel",
    "zwischen Salamandersteinen und Ongalo-Bergen",
    "zwischen Riva und Mengbilla",
    "zwischen Riva und Al‘Anfa",
    "südlich von Gerasim",
    "südlich des Blauen Sees",
    "nördlich von Havena-Perricum",
    "andere Seen",
    "Einsiedlersee",
    "Nordaventurien",
    "nördlich des Yaquirs",
    "Steineichenwald",
    "keine natürlichen Vorkommen",
    "ganz Aventurien",
    "Gjalskerland",
    "Westküste Aventuriens",
    "Hochgebirge Aventuriens"
  ],
  "Südosten": [
    "Aranien",
    "Küste südlich von Thorwal",
    "Raschtulswall",
    "Gorien",
    "Gorien, Aranien",
    "Zwischen Lowangen-Selem",
    "Garetien bis Echsensümpfe",
    "Ostaventurien",
    "südlich von Festum",
    "Süd- und Mittelaventurien",
    "Balash",
    "südlich von Havena-Perricum",
    "südlich von Havena",
    "nördlich von Drôl-Thalusa",
    "südlich von Neetha-Thalusa",
    "nördlich von Havena-Perricum",
    "nördlich von Grangor-Elburum",
    "aranisches Hochland",
    "Oron",
    "Südaventurien",
    "Unauer Berge",
    "Hochgebirge Aventuriens",
    "nördlich der Khôm",
    "nördlich des Yaquirs",
    "südlich von Riva",
    "Thalusien",
    "zwischen Gerasim und Mengbilla",
    "südlich der Gelben Sichel",
    "zwischen Salamandersteinen und Ongalo-Bergen",
    "zwischen Riva und Mengbilla",
    "zwischen Riva und Al‘Anfa",
    "südlich von Gerasim",
    "südlich des Blauen Sees",
    "Mhanadi",
    "andere Seen",
    "Elburische Küste",
    "keine natürlichen Vorkommen",
    "ganz Aventurien",
    "Mhanadistan",
    "Khunchom"
  ],
  "Südwesten": [
    "Almada",
    "Küste südlich von Thorwal",
    "Südl. Eternen",
    "Zwischen Lowangen-Selem",
    "nördlich der Khôm",
    "südlich Mengbilla",
    "Süd- und Mittelaventurien",
    "nördlich von Grangor-Elburum",
    "südlich von Loch Harodrôl",
    "nördlich von Drôl-Thalusa",
    "Zyklopeninseln",
    "südlich von Havena",
    "südlich von Neetha-Thalusa",
    "südlich der Gelben Sichel",
    "zwischen Salamandersteinen und Ongalo-Bergen",
    "zwischen Riva und Mengbilla",
    "zwischen Riva und Al‘Anfa",
    "südlich von Gerasim",
    "südlich des Blauen Sees",
    "südlich von Mengbilla",
    "südlich von Riva",
    "südlich von Havena-Perricum",
    "Pailos (Zyklopeninseln)",
    "südlich von Festum",
    "keine natürlichen Vorkommen",
    "nördlich des Yaquirs",
    "zwischen Gerasim und Mengbilla",
    "Amhalassih",
    "Südaventurien",
    "andere Seen",
    "Garetien bis Echsensümpfe",
    "Westküste zwischen Salza und Mengbilla",
    "ganz Aventurien",
    "Hochgebirge Aventuriens",
    "Liebliches Feld",
    "Westküste Aventuriens",
    "Westküste südlich Drôl"
  ],
  "Tiefer Süden": [
    "Alanfanische Plantagen",
    "Küste südlich von Thorwal",
    "westliches Regengebirge",
    "Zwischen Lowangen-Selem",
    "südlich von Loch Harodrôl",
    "Südl. Eternen",
    "Altoum",
    "andere Seen",
    "Shadif",
    "südlich von Havena",
    "südlich von Havena-Perricum",
    "Mysobien",
    "südlich von Riva",
    "Szintotal",
    "südlich von Festum",
    "südlich Mengbilla",
    "Südaventurien",
    "Echsensümpfe",
    "Süd- und Mittelaventurien",
    "Waldinseln",
    "keine natürlichen Vorkommen",
    "Souram",
    "Waldinseln von Ost-Altoum bis Ibonka",
    "ganz Aventurien",
    "Garetien bis Echsensümpfe",
    "Hochgebirge Aventuriens",
    "südlich von Mengbilla",
    "Westküste Aventuriens",
    "zwischen Mirham und Brabak",
    "südlich von Neetha-Thalusa",
    "südlich der Gelben Sichel",
    "zwischen Riva und Al‘Anfa",
    "südlich von Gerasim",
    "südlich des Blauen Sees",
    "Regengebirge",
    "Nikkali",
    "Westküste südlich Drôl"
  ]
};
