export const Nahkampfwaffen = [
{
"Name": "Albernischer Langdolch",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "55",
"BF": "14",
"VN": "Gegen mittlere Waffen nur AT -1. Gegen RS 4+ –1 TP."
},
{
"Name": "Bannschwert, klein",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "0",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "45",
"BF": "14",
"VN": ""
},
{
"Name": "Basiliskenzunge",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "50",
"BF": "14",
"VN": "Bei Hinterhalt +2 TP. Gegen Zwölfgötterkult-Tiere +1 TP (NL). Gegen Kultisten des Namenlosen +1 TP (Hesinde). Gegen Rüstungen RS 2 oder weniger –1 TP."
},
{
"Name": "Borndorn",
"Technik": "Dolche",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "0",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "65",
"BF": "10",
"VN": "-"
},
{
"Name": "Dolch",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "0",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "45",
"BF": "14",
"VN": "-"
},
{
"Name": "Drachenzahn",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "70",
"BF": "14",
"VN": "Gegen Echsenwesen +1 TP. Für Nichtzwerge –1 auf AT, PA und TP. Präziser Stich -1."
},
{
"Name": "Druidendolch",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-1",
"PA": "0",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "60",
"BF": "14",
"VN": ""
},
{
"Name": "Druidendolch aus Feuerstein",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-1",
"PA": "0",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "60",
"BF": "14",
"VN": "Bei RS 3 oder weniger RS -1. Bei RS 4+ RS +1."
},
{
"Name": "Druidendolch aus Vulkanglas",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-1",
"PA": "0",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "60",
"BF": "14",
"VN": "Bei RS 3 oder weniger RS -1. Bei RS 4+ RS +1."
},
{
"Name": "Eberfänger",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "1 Stn",
"Preis": "60",
"BF": "14",
"VN": "Gegen Tiere (mittel, klein) +1 TP. Kein Unterlaufen möglich."
},
{
"Name": "Federmesser",
"Technik": "Dolche",
"Leit": "GE/KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-1",
"PA": "-4",
"RW": "kurz",
"Gewicht": "0,2 Stn",
"Preis": "3",
"BF": "14",
"VN": "gegen Papier+4 TP, Kreuzblock nicht gegen Ketten-, Stangen-, Zweihandhiebwaffen"
},
{
"Name": "Firunsmesser",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "60",
"BF": "14",
"VN": "Gegen Tiere (mittel, klein) +1 TP. Kein Kreuzblock."
},
{
"Name": "Hakendolch",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-1",
"PA": "0",
"RW": "kurz",
"Gewicht": "1,25 Stn",
"Preis": "80",
"BF": "14",
"VN": "Erfolgreiche Parade: 1W6. Bei einer 1-2 Gegnerwaffe verhakt, Gegner AT -1 nächste KR (außer Unbewaffnete). Ab 19  bei AT Bestätigungswurf für Patzer."
},
{
"Name": "Jagdmesser",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,25 Stn",
"Preis": "50",
"BF": "14",
"VN": "Gegen Tiere (mittel, klein) +1 TP. Kein Kreuzblock gegen Zweihandwaffen."
},
{
"Name": "Katar",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "1,25 Stn",
"Preis": "50",
"BF": "14",
"VN": "Gegen Katzenwesen +2 TP. Bei Patzer Bestätigungswurf um 1 erhöht."
},
{
"Name": "Knochendolch",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "0",
"AT": "0",
"PA": "0",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "9",
"BF": "14",
"VN": "krit. Treffer zersplittern wählbar +W3 TP, RS 4+ -1 TP, nach Patzer zerbrochen"
},
{
"Name": "Langdolch",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "0",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "55",
"BF": "14",
"VN": "Gegen mittel nur AT -1, gegen RS 4+ -1 TP"
},
{
"Name": "Linkhand",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "0",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "90",
"BF": "14",
"VN": "Todesstoß ohne Erschwernis. Gegen RS 6+ –1 TP."
},
{
"Name": "Mengbilar",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "120",
"BF": "14",
"VN": "Zähigkeit bei Giftprobe -1, wenn es durch einen Mengbilar-Angriff. Gift geht nicht von Klinge ab. Gift kann beliebig ausgelöst werden. Bei Patzer Waffenbruch."
},
{
"Name": "Messer",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,25 Stn",
"Preis": "10",
"BF": "14",
"VN": "Gegen Seile und Netze +2 TP. Kreuzblock gegen Kettenwaffen, Stangenwaffen und Zweihandhiebwaffen nicht möglich."
},
{
"Name": "Ogerfänger",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "1 Stn",
"Preis": "100",
"BF": "14",
"VN": "Bei SP Widerhaken, Vergleich Kraftakt (Ziehen & Zerren) -> Raufen-AT -2 + Kraftakt (Ziehen & Zerren) -> 1W6+2 + QS SP. Bei erfolgreicher PA Kraftakt (Ziehen &
},
{
"Name": "Opferdolch",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "50",
"BF": "14",
"VN": "Bei Hinterhalt +2 TP. Gegen Zwölfgötterkult-Tiere +1 TP (NL). Gegen Rüstungen RS 2 oder weniger –1 TP."
},
{
"Name": "Scheibendolch",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-3",
"RW": "kurz",
"Gewicht": "1 Stn",
"Preis": "60",
"BF": "14",
"VN": "RS4+ RS -2, SP +1, kein Kreuzblock"
},
{
"Name": "Schere",
"Technik": "Dolche",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-4",
"RW": "kurz",
"Gewicht": "0,25 Stn",
"Preis": "5",
"BF": "14",
"VN": "gegen Seile und Netze +1 TP, Kreuzblock nicht gegen Ketten-, Stangen-, Zweihandhiebwaffen"
},
{
"Name": "Schneiderschere",
"Technik": "Dolche",
"Leit": "GE/KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-3",
"RW": "kurz",
"Gewicht": "0,3 Stn",
"Preis": "7",
"BF": "14",
"VN": "gegen Seile und Netze +1 TP, Kreuzblock nicht gegen Ketten-, Stangen-, Zweihandhiebwaffen"
},
{
"Name": "Schwerer Dolch",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "60",
"BF": "14",
"VN": "-"
},
{
"Name": "Shakagra-Giftdolch",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "0",
"RW": "kurz",
"Gewicht": "0,4 Stn",
"Preis": "80",
"BF": "14",
"VN": ""
},
{
"Name": "Waqqif",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "60",
"BF": "14",
"VN": "Bei RS 2 und weniger –1 RS. Präziser Stich nicht möglich."
},
{
"Name": "Windhager Drachenmesser",
"Technik": "Dolche",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "60",
"BF": "14",
"VN": "Gegen Drachen +1 TP. Gelten gegen Dämonen als magisch. 1 Stufe Furcht für Feen bis 7 m. Präziser Stich zusätzlich um 2 erschwert. Finte -1."
},
{
"Name": "Wurfdolch",
"Technik": "Dolche",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "-1",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "45",
"BF": "10",
"VN": "-"
},
{
"Name": "Wurfmesser",
"Technik": "Dolche",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "-1",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "30",
"BF": "10",
"VN": "-"
},
{
"Name": "Wurfring",
"Technik": "Dolche",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "-1",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,25 Stn",
"Preis": "30",
"BF": "10",
"VN": "-"
},
{
"Name": "Wurfscheibe",
"Technik": "Dolche",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "-1",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,25 Stn",
"Preis": "30",
"BF": "10",
"VN": "-"
},
{
"Name": "Wurfstern",
"Technik": "Dolche",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "-1",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,25 Stn",
"Preis": "30",
"BF": "10",
"VN": "-"
},
{
"Name": "Kriegsfächer",
"Technik": "Fächer",
"Leit": "GE",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-3",
"PA": "0",
"RW": "kurz",
"Gewicht": "1,25 Stn",
"Preis": "200",
"BF": "13",
"VN": "Angetäuschter Angriff +2 statt +1 TP, bei Patzer +2 SP"
},
{
"Name": "Degen",
"Technik": "Fechtwaffen",
"Leit": "GE",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "1",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "150",
"BF": "8",
"VN": "Präziser Stich um 1 erl., auch mit Kreuzblock keine PA gegen Kettenw. und Zweihandhiebw."
},
{
"Name": "Florett",
"Technik": "Fechtwaffen",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "1",
"PA": "0",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "300",
"BF": "8",
"VN": "Finte +1. Auch mit Kreuzblock nur Parade von Dolchen, Fechtwaffen und waffenlosen Angriffen."
},
{
"Name": "Magierdegen",
"Technik": "Fechtwaffen",
"Leit": "GE",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "2",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "250",
"BF": "8",
"VN": "Präziser Stich um 1 erl., auch mit Kreuzblock nur PA gegen Dolche, Fechtwaffen und waffenlose Angriffe"
},
{
"Name": "Rapier",
"Technik": "Fechtwaffen",
"Leit": "GE",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "1",
"PA": "0",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "200",
"BF": "8",
"VN": "-"
},
{
"Name": "Stockdegen",
"Technik": "Fechtwaffen",
"Leit": "GE",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "1",
"PA": "0",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "350",
"BF": "8",
"VN": "Um als Waffe zu identifizieren Sinnesschärfe. Verteidigung des Gegners nicht um 1 erschwert."
},
{
"Name": "Wolfsmesser",
"Technik": "Fechtwaffen",
"Leit": "GE",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "1",
"PA": "1",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "300",
"BF": "8",
"VN": "Bei gleichem INI-Wert zuerst dran. Für Nichtelfen –1 auf AT, PA und TP. Im beidhändigen Kampf in der gleichen KR AT -1 für zweite Waffe mit Reichweite mittel."
},
{
"Name": "Albernische Wurzelholzkeule",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "5",
"BF": "12",
"VN": "Zweihändig geführt +2 statt +1 TP. Betäubungsschlag 1W3+1 TP. Schildspalter nicht möglich."
},
{
"Name": "Albernischer Langbogen",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-3",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "80",
"BF": "4",
"VN": "-"
},
{
"Name": "Albernisches Wurfbeil",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "1,25 Stn",
"Preis": "100",
"BF": "10",
"VN": "-"
},
{
"Name": "Balestra",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-2",
"PA": "-3",
"RW": "kurz",
"Gewicht": "2,75 Stn",
"Preis": "200",
"BF": "6",
"VN": "-"
},
{
"Name": "Balestrina",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-3",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "120",
"BF": "6",
"VN": "-"
},
{
"Name": "Balläster",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-2",
"PA": "-3",
"RW": "kurz",
"Gewicht": "3 Stn",
"Preis": "200",
"BF": "6",
"VN": "-"
},
{
"Name": "Beil",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-1",
"PA": "-2",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "20",
"BF": "12",
"VN": ""
},
{
"Name": "Besen",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-1",
"PA": "-3",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "0,5",
"BF": "12",
"VN": "Betäubungsschlag zus. +1 TP, bei Patzer zerbrochen"
},
{
"Name": "Blasrohr",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "-",
"Bonus": "+1",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "40",
"BF": "10",
"VN": "-"
},
{
"Name": "Brabakbengel",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "-1",
"PA": "-2",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "170",
"BF": "12",
"VN": "Dornenspitze: 1W6+4 TP, bei RS 4+ –2 auf RS. Nach bestätigtem Attacke-Patzer 1 Stufe Betäubung."
},
{
"Name": "Bratpfanne",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "-1",
"PA": "-3",
"RW": "kurz",
"Gewicht": "2 Stn",
"Preis": "12",
"BF": "12",
"VN": ""
},
{
"Name": "Bratpfanne, heiß",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "-2",
"PA": "-3",
"RW": "kurz",
"Gewicht": "2 Stn",
"Preis": "12",
"BF": "12",
"VN": ""
},
{
"Name": "Bratspieß",
"Technik": "Hiebwaffen",
"Leit": "GE/KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-1",
"PA": "-2",
"RW": "mittel",
"Gewicht": "3 Stn",
"Preis": "16",
"BF": "12",
"VN": ""
},
{
"Name": "Brecheisen",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-1",
"PA": "-3",
"RW": "mittel",
"Gewicht": "5 Stn",
"Preis": "26",
"BF": "12",
"VN": ""
},
{
"Name": "Brett",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "0",
"BF": "12",
"VN": "Betäubungsschlag 1W3+1 TP. Bei bestätigtem Patzer zerbricht Waffe zusätzlich."
},
{
"Name": "Byakka",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "3,25 Stn",
"Preis": "90",
"BF": "12",
"VN": "Dornenspitze 1W6+4 TP, ab RS 5 RS -2, Nichtorks -1 auf AT, PA und TP, nach best. Patzer 1 Stufe Betäubung"
},
{
"Name": "Deichgabel",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-1",
"PA": "-2",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "30",
"BF": "12",
"VN": "Angriff mit Klinge 1W6+1 TP. Kettenrüstungen dagegen –2 RS. Nach erfolgreicher PA bis Ende  nächste KR AT -2."
},
{
"Name": "Dornenkeule",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "-1",
"PA": "-2",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "13",
"BF": "12",
"VN": "Bei Schaden +1 SP, bei Patzer zerbrochen"
},
{
"Name": "Eimer",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-3",
"PA": "-3",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "3",
"BF": "12",
"VN": ""
},
{
"Name": "Eisenwalder",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-2",
"PA": "-3",
"RW": "kurz",
"Gewicht": "3,75 Stn",
"Preis": "500",
"BF": "6",
"VN": "-"
},
{
"Name": "Elfenbogen",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-3",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "400",
"BF": "4",
"VN": "-"
},
{
"Name": "Fackel",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "",
"AT": "-1",
"PA": "-2",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "0,5",
"BF": "12",
"VN": ""
},
{
"Name": "Flasche",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-1",
"PA": "-3",
"RW": "kurz",
"Gewicht": "",
"Preis": "0",
"BF": "12",
"VN": ""
},
{
"Name": "Flasche, gesplittert",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-1",
"PA": "-4",
"RW": "kurz",
"Gewicht": "",
"Preis": "0",
"BF": "12",
"VN": ""
},
{
"Name": "Fleischerbeil",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "-1",
"PA": "-3",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "25",
"BF": "12",
"VN": "gegen Ungerüstete und Lederrüstung +1 TP, gegen RS 3+ -2 TP"
},
{
"Name": "Flöte",
"Technik": "Hiebwaffen",
"Leit": "GE",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "",
"AT": "-1",
"PA": "-4",
"RW": "kurz",
"Gewicht": "0,25 Stn",
"Preis": "2",
"BF": "12",
"VN": ""
},
{
"Name": "Gaoraith",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "1,25 Stn",
"Preis": "100",
"BF": "10",
"VN": "-"
},
{
"Name": "Handarmbrust",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-3",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "100",
"BF": "6",
"VN": "-"
},
{
"Name": "Handaxt",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-1",
"PA": "-2",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "20",
"BF": "12",
"VN": ""
},
{
"Name": "Handspiegel",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-3",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "60",
"BF": "12",
"VN": "Betäubungsschlag zus. +1 TP, bei Patzer zerbrochen"
},
{
"Name": "Hexenbesen",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "0",
"BF": "12",
"VN": "Betäubungsschlag 1W3+1 TP. Bei bestätigtem Patzer zerbricht Waffe zusätzlich."
},
{
"Name": "Immanschläger",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "1",
"BF": "12",
"VN": ""
},
{
"Name": "Ingerimmshammer",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "1,25 Stn",
"Preis": "125",
"BF": "12",
"VN": "Zetrümmern besserer von 2W6, Finte -1"
},
{
"Name": "Keule",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "3",
"BF": "12",
"VN": "Betäubungsschlag 1W3+1 TP. Bei bestätigtem Patzer zerbricht Waffe zusätzlich."
},
{
"Name": "Knochenkeule",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "0,6",
"BF": "12",
"VN": "krit. Treffer zersplittern wählbar +W3 TP, RS 4+ -1 TP, nach Patzer zerbrochen"
},
{
"Name": "Knüppel",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "0",
"BF": "12",
"VN": "Betäubungsschlag 1W3+1 TP. Bei bestätigtem Patzer zerbricht Waffe zusätzlich."
},
{
"Name": "Kompositbogen",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-3",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "160",
"BF": "4",
"VN": "-"
},
{
"Name": "Kriegsbogen",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-3",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "100",
"BF": "4",
"VN": "-"
},
{
"Name": "Kurzbogen",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-3",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "45",
"BF": "4",
"VN": "-"
},
{
"Name": "Langbogen",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-3",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "80",
"BF": "4",
"VN": "-"
},
{
"Name": "Laute",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-1",
"PA": "-3",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "150",
"BF": "12",
"VN": ""
},
{
"Name": "leichte Armbrust",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-2",
"PA": "-3",
"RW": "kurz",
"Gewicht": "3,25 Stn",
"Preis": "180",
"BF": "6",
"VN": "-"
},
{
"Name": "Lindwurmschläger",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "1 Stn",
"Preis": "90",
"BF": "12",
"VN": "Schildspalter +4 TP. Für Nichtzwerg –1 auf AT, PA und TP. AT -1 gegen große oder riesige Wesen."
},
{
"Name": "Magierkugel",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "-1",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "2 Stn",
"Preis": "30",
"BF": "10",
"VN": "-"
},
{
"Name": "Magierstab, kurz",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "40",
"BF": "12",
"VN": "Betäubungsschlag um 1 erleichtert. Vorstoß nicht möglich."
},
{
"Name": "Magierstab, mittel",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "60",
"BF": "12",
"VN": "Betäubungsschlag um 1 erleichtert. Vorstoß nicht möglich."
},
{
"Name": "Molokdeschnaja",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "1,25 Stn",
"Preis": "95",
"BF": "12",
"VN": "Einschüchtern (Drohung) +1 bei Drohgebärden. Im beidhändigen Kampf AT -1 und PA -1."
},
{
"Name": "Nostrischer Langbogen",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-3",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "100",
"BF": "4",
"VN": "-"
},
{
"Name": "Nudelholz",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-1",
"PA": "-2",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "10",
"BF": "12",
"VN": ""
},
{
"Name": "Oger-Keule (gr-ri)",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "22",
"Grundschaden": "2W6",
"Bonus": "+7",
"AT": "0",
"PA": "0",
"RW": "lang",
"Gewicht": "6 Stn",
"Preis": "10",
"BF": "12",
"VN": "nur große und riesige Wesen"
},
{
"Name": "Orknase",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "-1",
"PA": "-2",
"RW": "mittel",
"Gewicht": "1,75 Stn",
"Preis": "120",
"BF": "12",
"VN": "Schildspalter +4 TP. PA -1 gegen Angriffe von Dolchen und Fechtwaffen."
},
{
"Name": "Rabenschnabel",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "1,5 Stn",
"Preis": "105",
"BF": "12",
"VN": "Dornenspitze: 1W6+4 TP, RS 6+ –2 RS. Von Reittier aus +1 TP. Nach bestätigtem Patzer bei AT zusätzlich 1 Stufe Betäubung."
},
{
"Name": "Schmiedehammer",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "-3",
"RW": "mittel",
"Gewicht": "1,25 Stn",
"Preis": "100",
"BF": "12",
"VN": ""
},
{
"Name": "Schneidzahn",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "1 Stn",
"Preis": "80",
"BF": "10",
"VN": "-"
},
{
"Name": "schwere Armbrust",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-2",
"PA": "-3",
"RW": "kurz",
"Gewicht": "7,25 Stn",
"Preis": "360",
"BF": "6",
"VN": "-"
},
{
"Name": "Shakagra-Hammer",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "1,25 Stn",
"Preis": "175",
"BF": "12",
"VN": ""
},
{
"Name": "Shillelagh",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "5",
"BF": "12",
"VN": "Zweihändig geführt +2 statt +1 TP. Betäubungsschlag 1W3+1 TP. Schildspalter nicht möglich."
},
{
"Name": "Sichel",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-1",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,5 Stn",
"Preis": "10",
"BF": "12",
"VN": ""
},
{
"Name": "Sonnenzepter",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "1,25 Stn",
"Preis": "250",
"BF": "12",
"VN": "Am Tag PA +1, gegen Wesen mit AsP +1 TP. In der Nacht –1 AT. Gegen RS 4+ –1 TP."
},
{
"Name": "Steinbeil",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-1",
"PA": "-2",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "4",
"BF": "12",
"VN": "krit. Treffer nach Verd. +2 SP, RS4+ +1 RS, best. Patzer: zerbrechen"
},
{
"Name": "Steinhammer",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-3",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "20",
"BF": "12",
"VN": "krit. Treffer nach Verd. +2 SP, RS4+ +1 RS, best. Patzer: zerbrechen"
},
{
"Name": "Streitaxt",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "1,5 Stn",
"Preis": "105",
"BF": "12",
"VN": "-"
},
{
"Name": "Streitaxt der Streitenden Königreiche",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "1,5 Stn",
"Preis": "105",
"BF": "12",
"VN": "Schildspalter +1. Nach bestätigtem Patzer 1 Stufe Betäubung."
},
{
"Name": "Streitkolben",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "1,5 Stn",
"Preis": "105",
"BF": "12",
"VN": "-"
},
{
"Name": "Streitkolben der Streitenden Königreiche",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "1,5 Stn",
"Preis": "105",
"BF": "12",
"VN": "Von Reittier aus +1 TP. Nach bestätigtem Patzer bei Attacke 1 Stufe Betäubung."
},
{
"Name": "Stuhl",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "-2",
"PA": "-2",
"RW": "mittel",
"Gewicht": "",
"Preis": "",
"BF": "12",
"VN": ""
},
{
"Name": "Stuhlbein",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-1",
"PA": "-3",
"RW": "mittel",
"Gewicht": "",
"Preis": "",
"BF": "12",
"VN": ""
},
{
"Name": "Teigholz",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-1",
"PA": "-2",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "10",
"BF": "12",
"VN": ""
},
{
"Name": "Tisch",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "17",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "-4",
"PA": "-1",
"RW": "mittel",
"Gewicht": "",
"Preis": "",
"BF": "12",
"VN": ""
},
{
"Name": "Torfgabel",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "-1",
"PA": "-3",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "25",
"BF": "12",
"VN": "Ketten- und Plattenrüstungen RS –2. Erfolgreiche PA erschwert bis Ende nächster KR AT um 2."
},
{
"Name": "Windenarmbrust",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-2",
"PA": "-3",
"RW": "kurz",
"Gewicht": "7,25 Stn",
"Preis": "450",
"BF": "6",
"VN": "-"
},
{
"Name": "Wurfbeil",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "50",
"BF": "10",
"VN": "-"
},
{
"Name": "Wurfkeule",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "0",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "1 Stn",
"Preis": "5",
"BF": "10",
"VN": "-"
},
{
"Name": "Yeti-Keule (gr-ri)",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "18",
"Grundschaden": "2W6",
"Bonus": "+7",
"AT": "0",
"PA": "0",
"RW": "lang",
"Gewicht": "5,5 Stn",
"Preis": "9",
"BF": "12",
"VN": "nur große und riesige Wesen"
},
{
"Name": "Zauberkugel",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "-1",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "2 Stn",
"Preis": "30",
"BF": "10",
"VN": "-"
},
{
"Name": "Zauberstecken, kurz",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "30",
"BF": "12",
"VN": ""
},
{
"Name": "Zauberstecken, mittel",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "45",
"BF": "12",
"VN": ""
},
{
"Name": "Zaunpfahl",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "0",
"BF": "12",
"VN": "Betäubungsschlag 1W3+1 TP. Bei bestätigtem Patzer zerbricht Waffe zusätzlich."
},
{
"Name": "Zwergenskraja",
"Technik": "Hiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "100",
"BF": "12",
"VN": "Dornenspitze 1W6+2 TP mit RS -2 für RS4+, eingeengt Malus um 2 gesenkt, Nichtzwerge AT, PA und TP -2, nach erfolgr. Parade nächste AT -1"
},
{
"Name": "Geißel",
"Technik": "Kettenwaffen",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W3",
"Bonus": "0",
"AT": "-1",
"PA": "-",
"RW": "mittel",
"Gewicht": "1,5 Stn",
"Preis": "14",
"BF": "10",
"VN": "-"
},
{
"Name": "Kette",
"Technik": "Kettenwaffen",
"Leit": "KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "-2",
"PA": "-",
"RW": "mittel",
"Gewicht": "0,25 Stn",
"Preis": "0,3",
"BF": "10",
"VN": "Entwaffnen +2, Bestäötigung bei Patzer 2 höher"
},
{
"Name": "Kettenstab",
"Technik": "Kettenwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-",
"RW": "mittel",
"Gewicht": "2,5 Stn",
"Preis": "120",
"BF": "14",
"VN": "Entwaffnen +4, Bestätigung +1 bei Patzer"
},
{
"Name": "Morgenstern",
"Technik": "Kettenwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "0",
"PA": "-",
"RW": "mittel",
"Gewicht": "1,5 Stn",
"Preis": "110",
"BF": "10",
"VN": "-"
},
{
"Name": "Ochsenherde",
"Technik": "Kettenwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+6",
"AT": "-2",
"PA": "-",
"RW": "mittel",
"Gewicht": "6 Stn",
"Preis": "260",
"BF": "10",
"VN": "PA gegen Ochsenherde -3 statt -2. Bei Hammerschlag +2W6, höherer Würfel zählt. Nach bestätigtem oder unbestätigtem Patzer bei AT zusätzlich 1 Stufe Betäubung."
},
{
"Name": "Ogerschelle",
"Technik": "Kettenwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+2",
"AT": "-2",
"PA": "-",
"RW": "mittel",
"Gewicht": "4 Stn",
"Preis": "180",
"BF": "10",
"VN": "PA gegen Ogerschelle -3 statt -2. Bestätigter Patzer bei Attacke + 1 Stufe Betäubung +2 SP für Träger."
},
{
"Name": "Seife mit Tuch",
"Technik": "Kettenwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W3",
"Bonus": "",
"AT": "-1",
"PA": "-",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "1",
"BF": "10",
"VN": ""
},
{
"Name": "Wurfhaken mit Kletterseil",
"Technik": "Kettenwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-",
"RW": "lang",
"Gewicht": "1,5 Stn",
"Preis": "7,3",
"BF": "10",
"VN": ""
},
{
"Name": "Kriegslanze",
"Technik": "Lanzen",
"Leit": "-",
"Schwelle": "-",
"Grundschaden": "2W6",
"Bonus": "+6",
"AT": "-",
"PA": "-",
"RW": "-",
"Gewicht": "3,75 Stn",
"Preis": "100",
"BF": "6",
"VN": "Getroffener Fußkämpfer Körperbeherrschung (Kampfmanöver) -1 je 5 TP, sonst Liegend. Wenn AT vom Pferd gegen Ziel (klein, winzig) am Boden scheitert, Reiter
},
{
"Name": "Turnierlanze",
"Technik": "Lanzen",
"Leit": "-",
"Schwelle": "-",
"Grundschaden": "1W6",
"Bonus": "+8",
"AT": "-",
"PA": "-",
"RW": "-",
"Gewicht": "3 Stn",
"Preis": "30",
"BF": "6",
"VN": "-"
},
{
"Name": "Fuhrmannspeitsche",
"Technik": "Peitschen",
"Leit": "FF",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "",
"AT": "0",
"PA": "-",
"RW": "lang",
"Gewicht": "3 Stn",
"Preis": "20",
"BF": "4",
"VN": "-"
},
{
"Name": "Neunschwänzige",
"Technik": "Peitschen",
"Leit": "FF",
"Schwelle": "15",
"Grundschaden": "1W3",
"Bonus": "+1",
"AT": "-2",
"PA": "-",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "18",
"BF": "4",
"VN": "Gegner. Verteidigung -1, bei Patzer +1 SP"
},
{
"Name": "Neunschwänzige mit Dornen",
"Technik": "Peitschen",
"Leit": "FF",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-",
"RW": "mittel",
"Gewicht": "2,1 Stn",
"Preis": "25",
"BF": "4",
"VN": "Gegner. Verteidigung -1, bei Patzer +1 SP"
},
{
"Name": "Neunschwänzige mit Metallstücken",
"Technik": "Peitschen",
"Leit": "FF",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-",
"RW": "mittel",
"Gewicht": "2,1 Stn",
"Preis": "25",
"BF": "4",
"VN": "Gegner. Verteidigung -1, bei Patzer +1 SP"
},
{
"Name": "Bolzen",
"Technik": "Raufen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-3",
"PA": "-",
"RW": "kurz",
"Gewicht": "",
"Preis": "0,2",
"BF": "12",
"VN": "-"
},
{
"Name": "Diskus",
"Technik": "Raufen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "0",
"AT": "-2",
"PA": "-2",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "25",
"BF": "12",
"VN": "-"
},
{
"Name": "Orchidee",
"Technik": "Raufen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "1 Stn",
"Preis": "60",
"BF": "12",
"VN": "Bei PA kein halber Waffenschaden. Bei Angriffen mit Orchidee Paraden bewaffneter Gegner ohne Schaden. Bestätigter Patzer zerstört zusätzlich Waffe."
},
{
"Name": "Panzerarm",
"Technik": "Raufen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "0",
"RW": "kurz",
"Gewicht": "1 Stn",
"Preis": "70",
"BF": "12",
"VN": "Träger gilt gegenüber Bewaffneten auch als bewaffnet. Kein Haltegriff sowie Manöver, die auf dem Haltegriff beruhen. Verbergen (Gegenstand verbergen) -2."
},
{
"Name": "Pfeil",
"Technik": "Raufen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-",
"RW": "kurz",
"Gewicht": "",
"Preis": "0,4",
"BF": "12",
"VN": "-"
},
{
"Name": "Schlagring",
"Technik": "Raufen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "0",
"RW": "kurz",
"Gewicht": "0,25 Stn",
"Preis": "25",
"BF": "12",
"VN": "-"
},
{
"Name": "Veteranenhand",
"Technik": "Raufen",
"Leit": "GE/KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-2",
"RW": "kurz",
"Gewicht": "3 Stn",
"Preis": "150",
"BF": "12",
"VN": "bei bewaf. Parade gegen Hand kein Schaden, nach Patzer Bestätigungswurf um 2 erhöht"
},
{
"Name": "Waffenlos",
"Technik": "Raufen",
"Leit": "GE/KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "0",
"AT": "0",
"PA": "0",
"RW": "kurz",
"Gewicht": "",
"Preis": "0",
"BF": "",
"VN": ""
},
{
"Name": "Amazonenschild",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "",
"AT": "-5",
"PA": "2",
"RW": "kurz",
"Gewicht": "3,5 Stn",
"Preis": "85",
"BF": "10",
"VN": ""
},
{
"Name": "Bock",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-3",
"PA": "0",
"RW": "kurz",
"Gewicht": "3 Stn",
"Preis": "80",
"BF": "10",
"VN": "Entwaffnen möglich, keine Schilddeckung, keine Paraden gegen große Gegner"
},
{
"Name": "Buckler",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "",
"AT": "-3",
"PA": "0",
"RW": "kurz",
"Gewicht": "1 Stn",
"Preis": "40",
"BF": "10",
"VN": "Bei Kritischem Erfolg 1 Stufe Betäubung. Schilddeckung nicht möglich. Parade großer Gegner nicht möglich."
},
{
"Name": "Faustschild",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "",
"AT": "-3",
"PA": "0",
"RW": "kurz",
"Gewicht": "1 Stn",
"Preis": "40",
"BF": "10",
"VN": "Bei Kritischem Erfolg 1 Stufe Betäubung. Schilddeckung nicht möglich. Parade großer Gegner nicht möglich."
},
{
"Name": "Großer Lederschild",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "0",
"AT": "-5",
"PA": "2",
"RW": "kurz",
"Gewicht": "2,5 Stn",
"Preis": "45",
"BF": "10",
"VN": "Verteidigungshaltung PA +1. Schildstoß nur 1 TP."
},
{
"Name": "Großschild",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-6",
"PA": "3",
"RW": "kurz",
"Gewicht": "6 Stn",
"Preis": "100",
"BF": "10",
"VN": "Abwehr von Pfeilen und Bolzen PA +1. Bei gleichem INI-Wert später, GS -1."
},
{
"Name": "Havener Buckler",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-3",
"PA": "0",
"RW": "kurz",
"Gewicht": "1 Stn",
"Preis": "40",
"BF": "10",
"VN": "Bei Kritischen Erfolg zusätzlich 1 Stufe Betäubung. Schilddeckung nicht möglich, keine Parade von Attacken großer Gegner."
},
{
"Name": "Holzschild",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "",
"AT": "-4",
"PA": "1",
"RW": "kurz",
"Gewicht": "3,5 Stn",
"Preis": "50",
"BF": "10",
"VN": "-"
},
{
"Name": "Lederschild",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "",
"AT": "-4",
"PA": "1",
"RW": "kurz",
"Gewicht": "2 Stn",
"Preis": "30",
"BF": "10",
"VN": "Verteidigungshaltung PA +1. Schildstoß nur 1 TP."
},
{
"Name": "Shakagra-Buckler",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "",
"AT": "-3",
"PA": "1",
"RW": "kurz",
"Gewicht": "3 Stn",
"Preis": "250",
"BF": "10",
"VN": ""
},
{
"Name": "Shakagra-Langschild",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-5",
"PA": "3",
"RW": "kurz",
"Gewicht": "5 Stn",
"Preis": "500",
"BF": "10",
"VN": ""
},
{
"Name": "Thorwalerschild",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-5",
"PA": "2",
"RW": "kurz",
"Gewicht": "4,5 Stn",
"Preis": "70",
"BF": "10",
"VN": "Andere Waffe bei Sturmangriff +1 TP. Auf Reittier nur einfacher Schild-Bonus."
},
{
"Name": "Turnierschild",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "0",
"AT": "-4",
"PA": "1",
"RW": "kurz",
"Gewicht": "3,5 Stn",
"Preis": "30",
"BF": "10",
"VN": "-"
},
{
"Name": "Turnierschild der Streitenden Königreiche",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "",
"AT": "-4",
"PA": "1",
"RW": "kurz",
"Gewicht": "3,5 Stn",
"Preis": "30",
"BF": "10",
"VN": "-"
},
{
"Name": "Turschild",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-6",
"PA": "3",
"RW": "kurz",
"Gewicht": "7 Stn",
"Preis": "120",
"BF": "10",
"VN": "Abwehr von Pfeilen und Bolzen +2, schlägt erst bei gleicher INI, nach Patzer 1 Betäubung, GS -2"
},
{
"Name": "Verstärkter Holzschild",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "0",
"AT": "-4",
"PA": "1",
"RW": "kurz",
"Gewicht": "4 Stn",
"Preis": "70",
"BF": "10",
"VN": "Kraftakt +1 bei Schildstoß, nach vest. Patzer 1 Betäubung"
},
{
"Name": "Vollmetallbuckler",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-3",
"PA": "0",
"RW": "kurz",
"Gewicht": "1 Stn",
"Preis": "40",
"BF": "10",
"VN": "Bei Kritischen Erfolg zusätzlich 1 Stufe Betäubung. Schilddeckung nicht möglich, keine Parade von Attacken großer Gegner."
},
{
"Name": "Walschild",
"Technik": "Schilde",
"Leit": "KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-5",
"PA": "2",
"RW": "kurz",
"Gewicht": "3,5 Stn",
"Preis": "85",
"BF": "10",
"VN": "Sturmangriff andere Waffe TP +1, auf Reittier nur einfacher Bonus"
},
{
"Name": "Albernische Bauernwehr",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15/14",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "80",
"BF": "13",
"VN": "Wuchtschlag +1 TP. Nach bestätigtem Patzer Waffe verloren. Nach mindestens 5 KR Kampf Selbstbeherrschung (Schmerzen ignorieren), sonst 1 Stufe Schmerz."
},
{
"Name": "Albernisches Entermesser",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "120",
"BF": "13",
"VN": "Gegen Dolche, Fechtwaffen und Schwerter +1 PA. Droht Verlust durch Patzer oder Entwaffnung, 1W6: 1-2 nicht fallengelassen, keine AT bis Ende nächste KR. PA -1
},
{
"Name": "Albernisches Langschwert",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "-1",
"PA": "-1",
"RW": "mittel",
"Gewicht": "1,5 St",
"Preis": "180",
"BF": "13",
"VN": "Schildspalter möglich. Gegen Fechtwaffen und Schwerter +1 AT. Gegen Zweihandhiebwaffen und Zweihandschwerter PA -2."
},
{
"Name": "Amazonensäbel",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "200",
"BF": "13",
"VN": "Von einem Reittier aus geführt +2 TP. Gegen Zweihandhiebwaffen und Zweihandschwerter PA -2."
},
{
"Name": "Andergaster Langschwert",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "1,25 Stn",
"Preis": "200",
"BF": "13",
"VN": "Von Reittier aus +1 TP. Nach Patzer Bestätigungswurfes um 2 erhöht."
},
{
"Name": "Arbach",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "2,5 Stn",
"Preis": "120",
"BF": "13",
"VN": "Gegen RS 3 oder niedriger +1 TP. Nichtorks: -1 auf AT, PA und TP. Nicht zweihändig."
},
{
"Name": "Bannschwert, mittel",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "200",
"BF": "13",
"VN": ""
},
{
"Name": "Barbarenschwert",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "-1",
"PA": "-1",
"RW": "mittel",
"Gewicht": "1,5 Stn",
"Preis": "140",
"BF": "13",
"VN": "Einschüchtern (Drohung) bei Drohgebärden +1. Schildspalter möglich. Bei gleichem INI-Wert später. Bei bestätigtem AT-Patzer 1 Stufe Betäubung."
},
{
"Name": "Breitschwert",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "-1",
"PA": "-1",
"RW": "mittel",
"Gewicht": "1,5 Stn",
"Preis": "180",
"BF": "13",
"VN": "Schildspalter möglich. Gegen Zweihandhiebwaffen und Zweihandschwerter PA -2."
},
{
"Name": "Entermesser",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "120",
"BF": "13",
"VN": "In beengter Umgebung nur –2 auf AT und PA. PA -1 gegen Zweihandwaffen."
},
{
"Name": "Flammenschwert",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+7",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "1 AsP/KR",
"Preis": "0",
"BF": "",
"VN": ""
},
{
"Name": "Flammenschwert (fern)",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "99",
"Grundschaden": "1W6",
"Bonus": "+7",
"AT": "0",
"PA": "-",
"RW": "32 m | GS8",
"Gewicht": "2 AsP/KR",
"Preis": "0",
"BF": "",
"VN": ""
},
{
"Name": "Harbener Säbel",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "0,9 Stn",
"Preis": "200",
"BF": "13",
"VN": "Gegen RS 3 oder weniger +1 TP. Droht Verlust durch Patzer oder Entwaffnen, W6: 1-2 nicht fallengelassen, keine AT bis Ende nächste KR. PA -1 gegen
},
{
"Name": "Haumesser",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "100",
"BF": "13",
"VN": "Auch Hiebwaffen-Manöver möglich. Nicht zweihändig führbar."
},
{
"Name": "Hauswehr",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15/14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-1",
"PA": "-2",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "50",
"BF": "13",
"VN": "Wuchtschlag +1 TP. Nach bestätigtem Patzer Waffe verloren."
},
{
"Name": "Havener Messer",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "200",
"BF": "13",
"VN": "Gilt in beengter Umgebung als kurze Waffe. Binden nicht erschwert. PA -2 gegen Zweihandhiebwaffen und Zweihandschwerter. Wuchtschläge -1."
},
{
"Name": "Hirschfänger",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "1 Stn",
"Preis": "100",
"BF": "13",
"VN": "Gegen Tiere (mittel und größer) +1 TP. Unterlaufen nicht möglich."
},
{
"Name": "Khunchomer",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "1,25 Stn",
"Preis": "210",
"BF": "13",
"VN": "Bei Klingensturm Erschwernis auf beide Attacken sinkt um 1. Gegen RS 5+ –1 TP."
},
{
"Name": "Kurzschwert",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "0",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "140",
"BF": "13",
"VN": "Unterlaufen kombinierbar mit Wuchtschlag. PA -1 gegen Zweihandhiebwaffen und Zweihandschwerter."
},
{
"Name": "Kusliker Säbel",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "1,75 Stn",
"Preis": "160",
"BF": "13",
"VN": "Abzüge wenn beengt 1 niedriger, gegen RS 5+ -1TP"
},
{
"Name": "Langschwert",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "200",
"BF": "13",
"VN": "-"
},
{
"Name": "Nachtwind",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "1,75 Stn",
"Preis": "250",
"BF": "13",
"VN": "Bei zweihändiger Führung +2 statt +1 TP, PA-Erschwernis entfällt. CH -1 bei Gesellschaft (außer Einschüchtern, Menschenkenntnis und Willenskraft), wenn
},
{
"Name": "Nostrisches Langschwert",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "200",
"BF": "13",
"VN": "Von Reittier aus PA +1. Nach Patzer Bestätigungswurfes um 2 erhöht."
},
{
"Name": "Parazonium",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "140",
"BF": "13",
"VN": ""
},
{
"Name": "Richtschwert",
"Technik": "Schwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+6",
"AT": "-2",
"PA": "-3",
"RW": "mittel",
"Gewicht": "5 Stn",
"Preis": "600",
"BF": "13",
"VN": "Bei Kritischem Erfolg oder 16+ SP, alle Gegner in Angriffsdistanz Willenskraft (Einschüchtern widerstehen) -1, sonst 5 KR 1 Stufe Furcht. Treffer gegen den Kopf
},
{
"Name": "Robbentöter",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "1 Stn",
"Preis": "200",
"BF": "13",
"VN": "Gegen Tiere (mittel, groß) +1 TP. Für Nichtelfen –1 auf AT, PA und TP. Finte -1."
},
{
"Name": "Säbel",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "180",
"BF": "13",
"VN": "Von Reittier aus +1 TP. Gegen RS 4+ –1 TP an."
},
{
"Name": "Scimshar",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "kurz",
"Gewicht": "0,75 Stn",
"Preis": "140",
"BF": "13",
"VN": ""
},
{
"Name": "Seesäbel",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "180",
"BF": "13",
"VN": "In beengter Umgebung Abzüge auf AT und PA um 2 kleiner. Gegen RS 4+ –1 TP."
},
{
"Name": "Shakagra-Krummsäbel",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "200",
"BF": "13",
"VN": ""
},
{
"Name": "Shakagra-Schwert",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "200",
"BF": "13",
"VN": ""
},
{
"Name": "Sklaventod",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "1,25 Stn",
"Preis": "210",
"BF": "13",
"VN": "Gegen Humanoide mit RS 0 +1 TP. Naach erfolgreicher PA 1W6. Bei 6 hat sich Waffe verhakt, nächste AT -1 (nicht gegen Unbewaffnete)."
},
{
"Name": "Turnierschwert",
"Technik": "Schwerter",
"Leit": "GE/KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "0,5 Stn",
"Preis": "20",
"BF": "13",
"VN": "-"
},
{
"Name": "Drachentöter",
"Technik": "Spießwaffen",
"Leit": "GE/KK",
"Schwelle": "16",
"Grundschaden": "2W6",
"Bonus": "+6",
"AT": "0",
"PA": "-",
"RW": "überlang",
"Gewicht": "10 Stn",
"Preis": "1500",
"BF": "12",
"VN": "Gelingt AT 1, AT 2 +2, Ausweichen -4 und Fallenlassen"
},
{
"Name": "Pike",
"Technik": "Spießwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "0",
"PA": "-",
"RW": "überlang",
"Gewicht": "4,25 Stn",
"Preis": "50",
"BF": "12",
"VN": "in Formation Gegner AT-8, geg. Nahk. VT -4"
},
{
"Name": "Albernische Spießaxt",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15/14",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "0",
"PA": "-2",
"RW": "lang",
"Gewicht": "2,5 Stn",
"Preis": "160",
"BF": "12",
"VN": "Herunterstoßen nur um 2 erschwert. Pikenwall zusätzlich um 2 erschwert."
},
{
"Name": "Avesstab",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "2",
"RW": "lang",
"Gewicht": "0,75 Stn",
"Preis": "25",
"BF": "12",
"VN": "Zu Fall bringen +1. Sturmangriff -1."
},
{
"Name": "Berdysch",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "-1",
"PA": "-2",
"RW": "lang",
"Gewicht": "1,75 Stn",
"Preis": "50",
"BF": "12",
"VN": ""
},
{
"Name": "Cruaghairm",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "1",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "200",
"BF": "12",
"VN": "Bei Einsatz weitere Paraden in der gleichen Kampfrunde +1. Nach erfolgreicher PA W6: 1-2 verhakt, nächste Gegner-AT -1 (außer Unbewaffnete). Wuchtschlag TP -1.
},
{
"Name": "Dreizack",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "0",
"RW": "lang",
"Gewicht": "2 Stn",
"Preis": "80",
"BF": "12",
"VN": "Abzüge für Kampf im Wasser sinken um 2. Entwaffnen +1. Gegen RS 2+ –1 TP."
},
{
"Name": "Dreschflegel",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-2",
"PA": "-1",
"RW": "lang",
"Gewicht": "1,75 Stn",
"Preis": "30",
"BF": "12",
"VN": ""
},
{
"Name": "Dschadra",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "0",
"PA": "-1",
"RW": "lang",
"Gewicht": "2 Stn",
"Preis": "60",
"BF": "12",
"VN": "Vom Rücken eines Reittiers einsetzbar, auch für Sturmangriff. Zu Fall bringen -1."
},
{
"Name": "Efferdbart",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "1",
"RW": "lang",
"Gewicht": "2 Stn",
"Preis": "100",
"BF": "12",
"VN": "Gegen Wesen mit Tentakeln oder Fangarmen +1 TP. Kampf im Wasser-Abzüge 2 niedriger. Entwaffnen +1. Gegen RS 4+ –2 TP."
},
{
"Name": "Efferdbart",
"Technik": "Stangenwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-2",
"PA": "-2",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "100",
"BF": "10",
"VN": "-"
},
{
"Name": "Glefe",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "0",
"PA": "-2",
"RW": "lang",
"Gewicht": "2 Stn",
"Preis": "50",
"BF": "12",
"VN": "Mit weiterem Glefen-Kämpfer Wall möglich. Alle Kämpfer PA +1 oder Sturmangriff + 1TP. Pikenwall AT -1."
},
{
"Name": "Hakenspieß",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "-2",
"RW": "lang",
"Gewicht": "4 Stn",
"Preis": "70",
"BF": "12",
"VN": "Herunterstoßen +2, Finte -1"
},
{
"Name": "Hellebarde",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+6",
"AT": "0",
"PA": "-2",
"RW": "lang",
"Gewicht": "2,5 Stn",
"Preis": "160",
"BF": "12",
"VN": "Abzüge in beengter Umgebung auf AT und PA sinken um jeweils 2. Pikenwall -2."
},
{
"Name": "Hirtenstab",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "2",
"RW": "lang",
"Gewicht": "0,75 Stn",
"Preis": "10",
"BF": "12",
"VN": ""
},
{
"Name": "Holzspeer",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "0",
"RW": "lang",
"Gewicht": "1 Stn",
"Preis": "1",
"BF": "12",
"VN": "Gegen RS 2 oder niedriger +1 TP. Gegen RS 5+ –1 TP."
},
{
"Name": "Jagdspieß",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "0",
"PA": "-1",
"RW": "lang",
"Gewicht": "1,75 Stn",
"Preis": "80",
"BF": "12",
"VN": "Bei Festnageln Kraftakt Gegner bei Befreiung -1. Gegen Tiere (mittel, groß) +1 TP. Bei Festnageln gegen Tier 1W6: 5-6 Kraftakt, sonst Bruch."
},
{
"Name": "Kampfstab",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "0",
"PA": "2",
"RW": "lang",
"Gewicht": "1 Stn",
"Preis": "40",
"BF": "12",
"VN": "Zu Fall bringen +1. Sturmangriff -1."
},
{
"Name": "Kriegsflegel",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "-1",
"PA": "-1",
"RW": "lang",
"Gewicht": "2 Stn",
"Preis": "50",
"BF": "12",
"VN": "Schilde nur mit einfachem Bonus. Angriffe ab 19 möglicher Patzer. Auf Distanz halten nicht möglich."
},
{
"Name": "Magierstab, lang",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-1",
"PA": "2",
"RW": "lang",
"Gewicht": "0,75 Stn",
"Preis": "80",
"BF": "12",
"VN": "Betäubungsschlag um 1 erleichtert. Vorstoß nicht möglich."
},
{
"Name": "Magierstab, lang (aus Steineiche)",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-1",
"PA": "2",
"RW": "lang",
"Gewicht": "1 Stn",
"Preis": "380",
"BF": "12",
"VN": "Resistent gegen Feuer, sogar Drachenfeuer. Flammenschwert-Aktivierung für 2 AsP, nur 6 Punkte Volumen. Jeder Blitztreffer +3 TP."
},
{
"Name": "Neckerdreizack",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "0",
"RW": "lang",
"Gewicht": "2 Stn",
"Preis": "80",
"BF": "12",
"VN": "Keine Abzüge bei  Kampf im oder unter Wasser. Entwaffnen +1. An Land –1 TP."
},
{
"Name": "Neethaner Langaxt",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "0",
"PA": "-2",
"RW": "lang",
"Gewicht": "4 Stn",
"Preis": "120",
"BF": "12",
"VN": "Wuchtschlag +1 TP, Finte -2"
},
{
"Name": "Pailos",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "2W6",
"Bonus": "+3",
"AT": "-1",
"PA": "-2",
"RW": "lang",
"Gewicht": "4,5 Stn",
"Preis": "300",
"BF": "12",
"VN": ""
},
{
"Name": "Pailos",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "2W6",
"Bonus": "+3",
"AT": "-1",
"PA": "-2",
"RW": "lang",
"Gewicht": "4,5 Stn",
"Preis": "300",
"BF": "12",
"VN": "Rundumschlag +1, Finte -1"
},
{
"Name": "Partisane",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "-2",
"RW": "lang",
"Gewicht": "3,75 Stn",
"Preis": "100",
"BF": "12",
"VN": "Festnageln +2, Finte -1"
},
{
"Name": "Rimkur",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "0",
"PA": "-2",
"RW": "lang",
"Gewicht": "2,25 Stn",
"Preis": "250",
"BF": "12",
"VN": "Spitze 1W6+4 mit RS4+ RS -2, Festnageln und Zu Fall bringen +1, Nichtachaz AT, PA und TP -2, nach best. Patzer 1 Betäubung"
},
{
"Name": "Saufeder",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "0",
"PA": "-1",
"RW": "lang",
"Gewicht": "1,75 Stn",
"Preis": "100",
"BF": "12",
"VN": "Befreien aus Festnageln zusätzlich Erschwernis von 2 auf Kraftakt und +2 TP pro KR. Im Nahkampf Reichweite mittel."
},
{
"Name": "Schnitter",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "-1",
"PA": "-1",
"RW": "lang",
"Gewicht": "2 Stn",
"Preis": "80",
"BF": "12",
"VN": "Vorstoß AT +1. Sturmangriff -1."
},
{
"Name": "Sense",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "-2",
"PA": "-1",
"RW": "lang",
"Gewicht": "3,5 Stn",
"Preis": "40",
"BF": "12",
"VN": "Zu Fall bringen ohne SF möglich (dann -6 statt -4), bei Attacke oder Parade in KR nur max. GS/2."
},
{
"Name": "Skorpionspieß",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "1",
"PA": "-1",
"RW": "lang",
"Gewicht": "1,8 Stn",
"Preis": "5000",
"BF": "12",
"VN": "magisch, Giftkanal"
},
{
"Name": "Spealleagh",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "1",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "200",
"BF": "12",
"VN": "Bei Einsatz weitere Paraden in KR +1. Gegen Fliegende +1 AT und +1 PA. Gegner in vorteilhafter Position ohne Bonus. Wuchtschlag TP -1. Bei AT 19
},
{
"Name": "Speer",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "0",
"RW": "lang",
"Gewicht": "2 Stn",
"Preis": "45",
"BF": "12",
"VN": "-"
},
{
"Name": "Stoßspeer",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "0",
"PA": "-1",
"RW": "lang",
"Gewicht": "3,75 Stn",
"Preis": "100",
"BF": "12",
"VN": "Festnageln +1, daraus befreien -2, Nahkampf mittel"
},
{
"Name": "Sturmsense",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "-1",
"PA": "-1",
"RW": "lang",
"Gewicht": "1,75 Stn",
"Preis": "60",
"BF": "12",
"VN": "Mit weiterem gleichbewaffneten Kämpfer Sensenwall. Entweder PA +1 oder Sturmangriff TP +1. Bei 10+ TP W6. Bei 1 Klinge abgelöst."
},
{
"Name": "Usascoall",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15/14",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "0",
"PA": "-2",
"RW": "lang",
"Gewicht": "2,5 Stn",
"Preis": "160",
"BF": "12",
"VN": "Herunterstoßen nur um 2 erschwert. Pikenwall zusätzlich um 2 erschwert."
},
{
"Name": "Wanderstab",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "",
"AT": "0",
"PA": "2",
"RW": "lang",
"Gewicht": "1 Stn",
"Preis": "12",
"BF": "12",
"VN": ""
},
{
"Name": "Wanderstab (AM2)",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "0",
"PA": "2",
"RW": "lang",
"Gewicht": "0,75 Stn",
"Preis": "10",
"BF": "12",
"VN": ""
},
{
"Name": "Windhager Hakenaxt",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "1",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "200",
"BF": "12",
"VN": "Bei Einsatz weitere Paraden in der gleichen Kampfrunde +1. Nach erfolgreicher PA W6: 1-2 verhakt, nächste Gegner-AT -1 (außer Unbewaffnete). Wuchtschlag TP -1.
},
{
"Name": "Windhager Sichelspeer",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "1",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "200",
"BF": "12",
"VN": "Bei Einsatz weitere Paraden in KR +1. Gegen Fliegende +1 AT und +1 PA. Gegner in vorteilhafter Position ohne Bonus. Wuchtschlag TP -1. Bei AT 19
},
{
"Name": "Wurfspeer",
"Technik": "Stangenwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "-2",
"PA": "-2",
"RW": "mittel",
"Gewicht": "0,75 Stn",
"Preis": "40",
"BF": "10",
"VN": "-"
},
{
"Name": "Wurmspieß",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "-2",
"RW": "lang",
"Gewicht": "4 Stn",
"Preis": "120",
"BF": "12",
"VN": "Festnageln +2, gegen Drachen TP +2, Nichtzwerge AT, PA und TP -2, Finte -1"
},
{
"Name": "Zauberstab aus Steineiche",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-1",
"PA": "2",
"RW": "lang",
"Gewicht": "1 Stn",
"Preis": "380",
"BF": "12",
"VN": "Resistent gegen Feuer, sogar Drachenfeuer. Flammenschwert-Aktivierung für 2 AsP, nur 6 Punkte Volumen. Jeder Blitztreffer +3 TP."
},
{
"Name": "Zauberstecken, lang",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+2",
"AT": "-1",
"PA": "2",
"RW": "lang",
"Gewicht": "0,75 Stn",
"Preis": "60",
"BF": "12",
"VN": ""
},
{
"Name": "Zweililie",
"Technik": "Stangenwaffen",
"Leit": "GE/KK",
"Schwelle": "15",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "2",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "200",
"BF": "12",
"VN": "Weitere Paraden in derselben KR Erschwernis 1 niedriger. Wuchtschlag -1 TP."
},
{
"Name": "Barbarenstreitaxt",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "2W6",
"Bonus": "+4",
"AT": "0",
"PA": "-4",
"RW": "mittel",
"Gewicht": "3,5 Stn",
"Preis": "175",
"BF": "11",
"VN": "Bei Kritischem Erfolg oder 14+ SP alle Gegner in Angriffsdistanz Willenskraft (Einschüchtern widerstehen) -1 oder 1 Stufe Furcht für 5 KR. Bei bestätigtem AT-
},
{
"Name": "Brechstange",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "-1",
"PA": "-3",
"RW": "mittel",
"Gewicht": "6 Stn",
"Preis": "38",
"BF": "11",
"VN": ""
},
{
"Name": "Felsspalter",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "2W6",
"Bonus": "+2",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "3 Stn",
"Preis": "200",
"BF": "11",
"VN": "Hammerschlag +1. Zertrümmern nutzt 2W6, höherer Würfel zählt. Für Nichtzwerge –2 auf AT, PA und TP. Verkeilt nach Unbestätigtem Patzer in Wuchtschlag und
},
{
"Name": "Gruufhai",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+6",
"AT": "-1",
"PA": "-3",
"RW": "mittel",
"Gewicht": "4,5 Stn",
"Preis": "120",
"BF": "11",
"VN": "Wuchtschlag und Hammerschlag 2 leichter, Nichtorks AT, PA und TP -1, nach best. Patzer 1 Stufe Betäubung"
},
{
"Name": "Holzfälleraxt",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "2W6",
"Bonus": "+1",
"AT": "0",
"PA": "-4",
"RW": "mittel",
"Gewicht": "4 Stn",
"Preis": "80",
"BF": "11",
"VN": "Gegen Pflanzen +2 TP, gegen hölzerne Gegenstände +4 TP. Gegen Gegner RS 5+ –2 TP."
},
{
"Name": "Korspieß",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+6",
"AT": "0",
"PA": "-3",
"RW": "lang",
"Gewicht": "3,5 Stn",
"Preis": "400",
"BF": "11",
"VN": "Hammerschlag, Rundumschlag, Sturmangriff +1, Verteidigungshaltung +2 statt +4, Patzer-Bestätigung u 1 erhöht"
},
{
"Name": "Kriegshammer",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "2W6",
"Bonus": "+3",
"AT": "0",
"PA": "-3",
"RW": "mittel",
"Gewicht": "3 Stn",
"Preis": "170",
"BF": "11",
"VN": "-"
},
{
"Name": "Magierkugel",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-1",
"PA": "-4",
"RW": "kurz",
"Gewicht": "2 Stn",
"Preis": "30",
"BF": "11",
"VN": ""
},
{
"Name": "Oger-Keule (KK17+)",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "99",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "-6",
"PA": "-6",
"RW": "mittel",
"Gewicht": "6 Stn",
"Preis": "10",
"BF": "11",
"VN": "ab KK 17"
},
{
"Name": "Shakagra-Kriegshammer",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "2W6",
"Bonus": "+3",
"AT": "0",
"PA": "-3",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "250",
"BF": "11",
"VN": ""
},
{
"Name": "Spaten",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "-2",
"PA": "-4",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "8,5",
"BF": "11",
"VN": ""
},
{
"Name": "Spitzhacke",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+5",
"AT": "-1",
"PA": "-5",
"RW": "mittel",
"Gewicht": "2,75 Stn",
"Preis": "20",
"BF": "11",
"VN": ""
},
{
"Name": "Stakaxt",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "3 Stn",
"Preis": "40",
"BF": "11",
"VN": "Gegen hölzerne und steinerne Gegenstände +4 TP. Nach erfolgreicher PA bis zum Ende der nächsten KR AT -2."
},
{
"Name": "Troll-Axt (gr-ri)",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "26",
"Grundschaden": "3W6",
"Bonus": "+12",
"AT": "0",
"PA": "0",
"RW": "überlang",
"Gewicht": "12 Stn",
"Preis": "500",
"BF": "11",
"VN": "nur große und riesige Wesen"
},
{
"Name": "Troll-Axt (KK17+)",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "99",
"Grundschaden": "3W3",
"Bonus": "+6",
"AT": "-6",
"PA": "-6",
"RW": "mittel",
"Gewicht": "12 Stn",
"Preis": "500",
"BF": "11",
"VN": "ab KK 17"
},
{
"Name": "Vorschlaghammer",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+1",
"AT": "-1",
"PA": "-4",
"RW": "mittel",
"Gewicht": "5 Stn",
"Preis": "30",
"BF": "11",
"VN": "Betäubungsschlag zus. +1 TP, bei Patzer zerbrochen"
},
{
"Name": "Warunker Hammer",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+6",
"AT": "0",
"PA": "-3",
"RW": "lang",
"Gewicht": "3,75 Stn",
"Preis": "300",
"BF": "11",
"VN": "RS 4+ –1 RS. Nach bestätigtem Patzer zusätzlich 1 Stufe Betäubung."
},
{
"Name": "Yeti-Keule (KK17+)",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "99",
"Grundschaden": "1W6",
"Bonus": "+4",
"AT": "-6",
"PA": "-6",
"RW": "mittel",
"Gewicht": "5,5 Stn",
"Preis": "9",
"BF": "11",
"VN": "ab KK 17"
},
{
"Name": "Zauberkugel",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+1",
"AT": "-1",
"PA": "-4",
"RW": "kurz",
"Gewicht": "2 Stn",
"Preis": "30",
"BF": "11",
"VN": ""
},
{
"Name": "Zwergenschlägel",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+6",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "3 Stn",
"Preis": "100",
"BF": "11",
"VN": "In beengter Umgebung nur Abzüge von 2 auf Attacke und Parade. Wuchtschlag II/III +1 TP. Für Nichtzwerge –2 auf AT, PA und TP. Finte -1."
},
{
"Name": "Zyklopen-Hammer (gr-ri)",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "22",
"Grundschaden": "2W6",
"Bonus": "+12",
"AT": "0",
"PA": "0",
"RW": "überlang",
"Gewicht": "15 Stn",
"Preis": "700",
"BF": "11",
"VN": "nur große und riesige Wesen"
},
{
"Name": "Zyklopen-Hammer (KK21+)",
"Technik": "Zweihandhiebwaffen",
"Leit": "KK",
"Schwelle": "99",
"Grundschaden": "1W6",
"Bonus": "+6",
"AT": "-6",
"PA": "-6",
"RW": "mittel",
"Gewicht": "15 Stn",
"Preis": "700",
"BF": "11",
"VN": "ab KK 21"
},
{
"Name": "Albernischer Anderthalbhänder",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+6",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "2,25 Stn",
"Preis": "360",
"BF": "12",
"VN": "In beengter Umgebung nur Abzüge von –1 auf AT und PA. Finte -1."
},
{
"Name": "Andergaster",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+5",
"AT": "0",
"PA": "-4",
"RW": "mittel",
"Gewicht": "3,25 Stn",
"Preis": "400",
"BF": "12",
"VN": "Aktion mit Knauf oder Parierstange mit Ansage, Wechsel 1 freie Aktion, 1W6+3 TP, AT/PA-Mod 0/–2. Beengte Umgebung Abzüge auf AT/PA von –5/–5, statt –4/–4, wenn
},
{
"Name": "Anderthalbhänder",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+6",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "320",
"BF": "12",
"VN": "-"
},
{
"Name": "Bannschwert, groß",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+4",
"AT": "0",
"PA": "-3",
"RW": "mittel",
"Gewicht": "2,5 Stn",
"Preis": "360",
"BF": "12",
"VN": ""
},
{
"Name": "Bastardschwert",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "13",
"Grundschaden": "1W6",
"Bonus": "+6",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "3 Stn",
"Preis": "200",
"BF": "12",
"VN": "Vorstoß Bonus +3 statt +2, Verteidigungshaltung nur +3 statt +4."
},
{
"Name": "Boronssichel",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+3",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "4 Stn",
"Preis": "400",
"BF": "12",
"VN": "Herunterstoßen möglich, gegen Reittiere +2 TP, Eingeengt je zus. -2"
},
{
"Name": "Doppelkhunchomer",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+3",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "320",
"BF": "12",
"VN": "Bei Kritischem Erfolg Bestätigung +2. Keine Finten möglich."
},
{
"Name": "Eichhafener",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+5",
"AT": "0",
"PA": "-4",
"RW": "mittel",
"Gewicht": "3,5 Stn",
"Preis": "440",
"BF": "12",
"VN": "Gegner mit kurzen oder mittleren Waffen AT –1. Aktion mit Knauf oder Parierstange nach Ansage, Wechsel 1 freie Aktion, 1W6+3 TP, AT/PA-Mod –1/–2. Beengte
},
{
"Name": "Großer Sklaventod",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+3",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "320",
"BF": "12",
"VN": "Einschüchtern (Drohung) bei Drohgebärden +1. Gegen Humanoide mit RS 0 +1 TP. Bei erfolgreicher Parade 1W6: 5 oder 6 verhaken, nächste AT -1 (nicht gegen
},
{
"Name": "Harmlyner",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+5",
"AT": "0",
"PA": "-4",
"RW": "mittel",
"Gewicht": "3,5 Stn",
"Preis": "440",
"BF": "12",
"VN": "Gegner mit kurzen oder mittleren Waffen AT –1. Aktion mit Knauf oder Parierstange nach Ansage, Wechsel 1 freie Aktion, 1W6+3 TP, AT/PA-Mod –1/–2. Beengte
},
{
"Name": "Nostrianer",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+5",
"AT": "0",
"PA": "-4",
"RW": "mittel",
"Gewicht": "3,25 Stn",
"Preis": "400",
"BF": "12",
"VN": "Aktion mit Knauf oder Parierstange mit Ansage, Wechsel 1 freie Aktion, 1W6+3 TP, AT/PA-Mod 0/–2. Beengte Umgebung Abzüge auf AT/PA von –5/–5, statt –4/–4, wenn
},
{
"Name": "Opallöwin",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+5",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "-",
"BF": "12",
"VN": "Hohe Klinge oder Weiter Schwung +1 TP. Wuchtschläge um 1 erschwert, Schildspalter -4 TP."
},
{
"Name": "Rondrakamm",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+2",
"AT": "0",
"PA": "-1",
"RW": "mittel",
"Gewicht": "2 Stn",
"Preis": "340",
"BF": "12",
"VN": "Windmühle +1 TP. Schnellziehen nicht möglich."
},
{
"Name": "Turnierzweihänder",
"Technik": "Zweihandschwerter",
"Leit": "GE/KK",
"Schwelle": "16",
"Grundschaden": "1W6",
"Bonus": "+3",
"AT": "0",
"PA": "-2",
"RW": "mittel",
"Gewicht": "2,25 Stn",
"Preis": "40",
"BF": "12",
"VN": "-"
},
{
"Name": "Tuzakmesser",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "1W6",
"Bonus": "+6",
"AT": "0",
"PA": "0",
"RW": "mittel",
"Gewicht": "1,75 Stn",
"Preis": "360",
"BF": "12",
"VN": "Hohe Klinge oder Weiter Schwung +1 TP. Wuchtschläge um 1 erschwert. Schildspalter -4 TP."
},
{
"Name": "Zweihänder",
"Technik": "Zweihandschwerter",
"Leit": "KK",
"Schwelle": "14",
"Grundschaden": "2W6",
"Bonus": "+4",
"AT": "0",
"PA": "-3",
"RW": "mittel",
"Gewicht": "2,5 Stn",
"Preis": "360",
"BF": "12",
"VN": "-"
}];
